***UserEntryIDfor2013surveys=TEXT(IFBLANK(USER_ENTRY_ID("0aa16d31-9cb5-46e3-801c-b52fb5819792"), USER_ENTRY_ID("5b0fbf1e-04ae-4a5c-bb12-6c502d720941")))
***DISPLAY_NAME=DISPLAY_NAME()
***Type=PARTICIPANT_FIELD(1)
***PIIF=PARTICIPANT_FIELD(2)
***Submitted=RESPONSE("PRI reporting framework 2013/2014 (Template - 3 surveys): (CM_05_A) . . . . . . . . Q. I hereby submit my response", "b998efce06f441a196f509b4bbebd8fa_1", "ccea9fd7-d822-45a8-be4d-48897d71855f")
***IFI_Confirm=RESPONSE("PRI reporting framework 2013/2014 (Template - 3 surveys): (1.11.1.7.1) Q Confirm response to this module Y", "4812bb63a9174894b8f2b16151b2f932_13", "ccea9fd7-d822-45a8-be4d-48897d71855f")
***Size=TEXT(PARTICIPANT_FIELD(14))
***Signed_PRI=TEXT(PARTICIPANT_FIELD(17))
***Region=TEXT(PARTICIPANT_FIELD(16))
***Country=TEXT(PARTICIPANT_FIELD(6))
***IF_Internal=RESPONSE_IGNORE_STATUS("(OO_05.1_M1_A) Q (no name)","67c7896f98114999a55bf099023d8975_58","ccea9fd7-d822-45a8-be4d-48897d71855f")
***IF_External=RESPONSE_IGNORE_STATUS("(OO_05.1_M2_A) Q (no name)","67c7896f98114999a55bf099023d8975_59","ccea9fd7-d822-45a8-be4d-48897d71855f")
***OO_11_IFD=RESPONSE("PRI reporting framework 2013/2014 (Template - 3 surveys): (OO_11.1_L) Q Inclusive finance Choice", "23a0324f1e21444e9eb7536f51697590", "ccea9fd7-d822-45a8-be4d-48897d71855f")
***OO_11_IFI=RESPONSE("PRI reporting framework 2013/2014 (Template - 3 surveys): (OO_11.2_L) Q Inclusive finance Choice", "3688cf567f70453b919b326b5dde53c0", "ccea9fd7-d822-45a8-be4d-48897d71855f")
***OO_12_IFD=RESPONSE("PRI reporting framework 2013/2014 (Template - 3 surveys): (OO_12.1_I) Qi Inclusive Finance Choice", "c28ac6281cca49f78914bc505a3e9b8d", "ccea9fd7-d822-45a8-be4d-48897d71855f")
***OO_12_IFI=RESPONSE("PRI reporting framework 2013/2014 (Template - 3 surveys): (OO_12.1_K) Q Inclusive Finance Choice", "ae80c24cbeed497d88273a7bfc125265", "ccea9fd7-d822-45a8-be4d-48897d71855f")
***IFI_02_1=SCORE("PRI reporting framework 2013/2014: (1.11.1.3.1.2) . . . . . . Q02.1. Indicate if you have due diligence policies and/or procedures in place for the selection of external investment managers in inclusive finance that take their approach to the following responsible investment issues (PIIF Principles) into account:", "7428bb644b2549f1b79280084be81153", "ccea9fd7-d822-45a8-be4d-48897d71855f")
***IFI_02_1_a=SCORE("PRI reporting framework 2013/2014: (1.11.1.3.1.2.1) . . . . . . . Q. Actively supporting retail providers to innovate and expand the range of financial services available to low income people  (Principle 1)", "285b4345eda348d4bcd784a9e09775df", "ccea9fd7-d822-45a8-be4d-48897d71855f")
***IFI_02_1_a_Y=SCORE("PRI reporting framework 2013/2014: (1.11.1.3.1.2.1.1) . . . . . . . . Q. Yes", "16192dba894d467c96aabcd5632bbd33", "ccea9fd7-d822-45a8-be4d-48897d71855f")
***IFI_02_1_a_N=SCORE("PRI reporting framework 2013/2014: (1.11.1.3.1.2.1.2) . . . . . . . . Q. No", "6277e61a7d784f34aa9824af21a46e9d", "ccea9fd7-d822-45a8-be4d-48897d71855f")
***IFI_02_1_b=SCORE("PRI reporting framework 2013/2014: (1.11.1.3.1.2.2) . . . . . . . Q. Integration of client protection in investment policies and practices. (Principle 2)", "eaa850cbb4844f189081dad506fc4e54", "ccea9fd7-d822-45a8-be4d-48897d71855f")
***IFI_02_1_b_Y=SCORE("PRI reporting framework 2013/2014: (1.11.1.3.1.2.2.1) . . . . . . . . Q. Yes", "16192dba894d467c96aabcd5632bbd33_1", "ccea9fd7-d822-45a8-be4d-48897d71855f")
***IFI_02_1_b_N=SCORE("PRI reporting framework 2013/2014: (1.11.1.3.1.2.2.2) . . . . . . . . Q. No", "6277e61a7d784f34aa9824af21a46e9d_1", "ccea9fd7-d822-45a8-be4d-48897d71855f")
***IFI_02_1_c=SCORE("PRI reporting framework 2013/2014: (1.11.1.3.1.2.3) . . . . . . . Q. Treating investees fairly with appropriate financing that meets demand, clear and balanced contracts, and fair processes for resolving disputes. (Principle 3)", "12a843ada439455db8535ac2338cc2f3", "ccea9fd7-d822-45a8-be4d-48897d71855f")
***IFI_02_1_c_Y=SCORE("PRI reporting framework 2013/2014: (1.11.1.3.1.2.3.1) . . . . . . . . Q. Yes", "16192dba894d467c96aabcd5632bbd33_2", "ccea9fd7-d822-45a8-be4d-48897d71855f")
***IFI_02_1_c_N=SCORE("PRI reporting framework 2013/2014: (1.11.1.3.1.2.3.2) . . . . . . . . Q. No", "6277e61a7d784f34aa9824af21a46e9d_2", "ccea9fd7-d822-45a8-be4d-48897d71855f")
***IFI_02_1_d=SCORE("PRI reporting framework 2013/2014: (1.11.1.3.1.2.4) . . . . . . . Q. The inclusion of environmental, social and corporate governance (ESG) issues in investment policies and reporting. (Principle 4)", "2820fab49a484006ae5d6d51fb6e3689", "ccea9fd7-d822-45a8-be4d-48897d71855f")
***IFI_02_1_d_Y=SCORE("PRI reporting framework 2013/2014: (1.11.1.3.1.2.4.1) . . . . . . . . Q. Yes", "16192dba894d467c96aabcd5632bbd33_3", "ccea9fd7-d822-45a8-be4d-48897d71855f")
***IFI_02_1_d_N=SCORE("PRI reporting framework 2013/2014: (1.11.1.3.1.2.4.2) . . . . . . . . Q. No", "6277e61a7d784f34aa9824af21a46e9d_3", "ccea9fd7-d822-45a8-be4d-48897d71855f")
***IFI_02_1_e=SCORE("PRI reporting framework 2013/2014: (1.11.1.3.1.2.5) . . . . . . . Q. Active promotion of transparency in all aspects. (Principle 5)", "fc35d1efbc544fc7879278e8b81915e1", "ccea9fd7-d822-45a8-be4d-48897d71855f")
***IFI_02_1_e_Y=SCORE("PRI reporting framework 2013/2014: (1.11.1.3.1.2.5.1) . . . . . . . . Q. Yes", "16192dba894d467c96aabcd5632bbd33_4", "ccea9fd7-d822-45a8-be4d-48897d71855f")
***IFI_02_1_e_N=SCORE("PRI reporting framework 2013/2014: (1.11.1.3.1.2.5.2) . . . . . . . . Q. No", "6277e61a7d784f34aa9824af21a46e9d_4", "ccea9fd7-d822-45a8-be4d-48897d71855f")
***IFI_02_1_f=SCORE("PRI reporting framework 2013/2014: (1.11.1.3.1.2.6) . . . . . . . Q. Striving for a balanced long-term social and financial risk-adjusted return that recognises the interests of clients, retail providers and investors. (Principle 6)", "1e67eb35a0dd4cd882c5f677b4895fb7", "ccea9fd7-d822-45a8-be4d-48897d71855f")
***IFI_02_1_f_Y=SCORE("PRI reporting framework 2013/2014: (1.11.1.3.1.2.6.1) . . . . . . . . Q. Yes", "16192dba894d467c96aabcd5632bbd33_5", "ccea9fd7-d822-45a8-be4d-48897d71855f")
***IFI_02_1_f_N=SCORE("PRI reporting framework 2013/2014: (1.11.1.3.1.2.6.2) . . . . . . . . Q. No", "6277e61a7d784f34aa9824af21a46e9d_5", "ccea9fd7-d822-45a8-be4d-48897d71855f")
***IFI_02_1_g=SCORE("PRI reporting framework 2013/2014: (1.11.1.3.1.2.7) . . . . . . . Q. Collaborating to set harmonised investor standards that support the further development of inclusive finance. (Principle 7)", "4e014f75f4a940699c0e49104c18e00f", "ccea9fd7-d822-45a8-be4d-48897d71855f")
***IFI_02_1_g_Y=SCORE("PRI reporting framework 2013/2014: (1.11.1.3.1.2.7.1) . . . . . . . . Q. Yes", "16192dba894d467c96aabcd5632bbd33_6", "ccea9fd7-d822-45a8-be4d-48897d71855f")
***IFI_02_1_g_N=SCORE("PRI reporting framework 2013/2014: (1.11.1.3.1.2.7.2) . . . . . . . . Q. No", "6277e61a7d784f34aa9824af21a46e9d_6", "ccea9fd7-d822-45a8-be4d-48897d71855f")
***IFI_02_sum=VALUE(IFI_02_1_a_Y)+VALUE(IFI_02_1_a_N)+VALUE(IFI_02_1_b_Y)+VALUE(IFI_02_1_b_N)+VALUE(IFI_02_1_c_Y)+VALUE(IFI_02_1_c_N)+VALUE(IFI_02_1_d_Y)+VALUE(IFI_02_1_d_N)+VALUE(IFI_02_1_e_Y)+VALUE(IFI_02_1_e_N)+VALUE(IFI_02_1_f_Y)+VALUE(IFI_02_1_f_N)+VALUE(IFI_02_1_g_Y)+VALUE(IFI_02_1_g_N)
***IFI_02_SCORE=VALUE(
IF((IFI_02_sum)<100, "0",
IF((IFI_02_sum)<300, "1",
IF((IFI_02_sum)<500, "2",
IF((IFI_02_sum)>=500, "3"))
))))
***IFI_03_1=SCORE("PRI reporting framework 2013/2014: (1.11.1.4.1.2) . . . . . . Q03.1. When agreeing contracts and designing mandates with investment managers, in the process, indicate if you consider including the following issues referred to in the PIIF:", "dfae3fc51ba646a7a4bed13d3ffe3f22", "ccea9fd7-d822-45a8-be4d-48897d71855f")
***IFI_03_1_a=SCORE("PRI reporting framework 2013/2014: (1.11.1.4.1.2.1) . . . . . . . Q. Actively supporting retail providers to innovate and expand the range of financial services to low-income people (Principle 1)", "fe206b7911a54daf98d8a8612247953f", "ccea9fd7-d822-45a8-be4d-48897d71855f")
***IFI_03_1_a_Y=SCORE("PRI reporting framework 2013/2014: (1.11.1.4.1.2.1.1) . . . . . . . . Q. Yes", "ba4575140e5a49549de69928e16d345a", "ccea9fd7-d822-45a8-be4d-48897d71855f")
***IFI_03_1_a_N=SCORE("PRI reporting framework 2013/2014: (1.11.1.4.1.2.1.2) . . . . . . . . Q. No", "0dcbc09a7a064d4cacec4752ea84ef6a", "ccea9fd7-d822-45a8-be4d-48897d71855f")
***IFI_03_1_b=SCORE("PRI reporting framework 2013/2014: (1.11.1.4.1.2.2) . . . . . . . Q. Integration of client protection in investment policies and practices (Principle 2)", "8b89e4546126454d81431f00274f45c0", "ccea9fd7-d822-45a8-be4d-48897d71855f")
***IFI_03_1_b_Y=SCORE("PRI reporting framework 2013/2014: (1.11.1.4.1.2.2.1) . . . . . . . . Q. Yes", "ba4575140e5a49549de69928e16d345a_1", "ccea9fd7-d822-45a8-be4d-48897d71855f")
***IFI_03_1_b_N=SCORE("PRI reporting framework 2013/2014: (1.11.1.4.1.2.2.2) . . . . . . . . Q. No", "0dcbc09a7a064d4cacec4752ea84ef6a_1", "ccea9fd7-d822-45a8-be4d-48897d71855f")
***IFI_03_1_c=SCORE("PRI reporting framework 2013/2014: (1.11.1.4.1.2.3) . . . . . . . Q. Treating investees fairly with appropriate financing needs that meets demand, clear and balanced contracts and fair processes for resolving disputes (Principle 3)", "4347564ec9344caab528bfc5f438e440", "ccea9fd7-d822-45a8-be4d-48897d71855f")
***IFI_03_1_c_Y=SCORE("PRI reporting framework 2013/2014: (1.11.1.4.1.2.3.1) . . . . . . . . Q. Yes", "ba4575140e5a49549de69928e16d345a_2", "ccea9fd7-d822-45a8-be4d-48897d71855f")
***IFI_03_1_c_N=SCORE("PRI reporting framework 2013/2014: (1.11.1.4.1.2.3.2) . . . . . . . . Q. No", "0dcbc09a7a064d4cacec4752ea84ef6a_2", "ccea9fd7-d822-45a8-be4d-48897d71855f")
***IFI_03_1_d=SCORE("PRI reporting framework 2013/2014: (1.11.1.4.1.2.4) . . . . . . . Q. The inclusion of ESG issues in investment policies and reporting (Principle 4)", "e7eafee5d39549a19f9ae03dc49f001d", "ccea9fd7-d822-45a8-be4d-48897d71855f")
***IFI_03_1_d_Y=SCORE("PRI reporting framework 2013/2014: (1.11.1.4.1.2.4.1) . . . . . . . . Q. Yes", "ba4575140e5a49549de69928e16d345a_3", "ccea9fd7-d822-45a8-be4d-48897d71855f")
***IFI_03_1_d_N=SCORE("PRI reporting framework 2013/2014: (1.11.1.4.1.2.4.2) . . . . . . . . Q. No", "0dcbc09a7a064d4cacec4752ea84ef6a_3", "ccea9fd7-d822-45a8-be4d-48897d71855f")
***IFI_03_1_e=SCORE("PRI reporting framework 2013/2014: (1.11.1.4.1.2.5) . . . . . . . Q. Active promotion of transparency in all aspects (Principle 5)", "2d6ad9669d1a43c184601076200ad46d", "ccea9fd7-d822-45a8-be4d-48897d71855f")
***IFI_03_1_e_Y=SCORE("PRI reporting framework 2013/2014: (1.11.1.4.1.2.5.1) . . . . . . . . Q. Yes", "ba4575140e5a49549de69928e16d345a_4", "ccea9fd7-d822-45a8-be4d-48897d71855f")
***IFI_03_1_e_N=SCORE("PRI reporting framework 2013/2014: (1.11.1.4.1.2.5.2) . . . . . . . . Q. No", "0dcbc09a7a064d4cacec4752ea84ef6a_4", "ccea9fd7-d822-45a8-be4d-48897d71855f")
***IFI_03_1_f=SCORE("PRI reporting framework 2013/2014: (1.11.1.4.1.2.6) . . . . . . . Q. Striving for a balanced long-term social and financial risk-adjusted return that recognises the interests of clients, retail providers and investors (Principle 6)", "a1dc519caba44ea59701654277a67dcd", "ccea9fd7-d822-45a8-be4d-48897d71855f")
***IFI_03_1_f_Y=SCORE("PRI reporting framework 2013/2014: (1.11.1.4.1.2.6.1) . . . . . . . . Q. Yes", "ba4575140e5a49549de69928e16d345a_5", "ccea9fd7-d822-45a8-be4d-48897d71855f")
***IFI_03_1_f_N=SCORE("PRI reporting framework 2013/2014: (1.11.1.4.1.2.6.2) . . . . . . . . Q. No", "0dcbc09a7a064d4cacec4752ea84ef6a_5", "ccea9fd7-d822-45a8-be4d-48897d71855f")
***IFI_03_1_g=SCORE("PRI reporting framework 2013/2014: (1.11.1.4.1.2.7) . . . . . . . Q. Collaborating to set harmonised investor standards that support the further development of inclusive finance (Principle 7)", "c5a6c3e215bf4020a1b3d6d87bb0f320", "ccea9fd7-d822-45a8-be4d-48897d71855f")
***IFI_03_1_g_Y=SCORE("PRI reporting framework 2013/2014: (1.11.1.4.1.2.7.1) . . . . . . . . Q. Yes", "ba4575140e5a49549de69928e16d345a_6", "ccea9fd7-d822-45a8-be4d-48897d71855f")
***IFI_03_1_g_N=SCORE("PRI reporting framework 2013/2014: (1.11.1.4.1.2.7.2) . . . . . . . . Q. No", "0dcbc09a7a064d4cacec4752ea84ef6a_6", "ccea9fd7-d822-45a8-be4d-48897d71855f")
***IFI_03_sum=VALUE(IFI_03_1_a_Y)+VALUE(IFI_03_1_a_N)+VALUE(IFI_03_1_b_Y)+VALUE(IFI_03_1_b_N)+VALUE(IFI_03_1_c_Y)+VALUE(IFI_03_1_c_N)+VALUE(IFI_03_1_d_Y)+VALUE(IFI_03_1_d_N)+VALUE(IFI_03_1_e_Y)+VALUE(IFI_03_1_e_N)+VALUE(IFI_03_1_f_Y)+VALUE(IFI_03_1_f_N)+VALUE(IFI_03_1_g_Y)+VALUE(IFI_03_1_g_N)
***IFI_03_SCORE=VALUE(
IF((IFI_03_sum)<100, "0",
IF((IFI_03_sum)<300, "1",
IF((IFI_03_sum)<500, "2",
IF((IFI_03_sum)>=500, "3"))
))))
***IFI_04_1=SCORE("PRI reporting framework 2013/2014: (1.11.1.5.1.2) . . . . . . Q04.1. Indicate if you monitor your current investment managers’ implementation of the PIIF principles.", "760b7535979c4086a3519e664ade3d42", "ccea9fd7-d822-45a8-be4d-48897d71855f")
***IFI_04_1_Y=SCORE("PRI reporting framework 2013/2014: (1.11.1.5.1.2.1) . . . . . . . Q. Yes", "f8fa2e3ec3c441789556043d17d77dc9", "ccea9fd7-d822-45a8-be4d-48897d71855f")
***IFI_04_2=SCORE("PRI reporting framework 2013/2014: (1.11.1.5.1.2.1.1) . . . . . . . . Q04.2. Indicate the frequency of reporting you typically require.", "47101455894a460ebf6ddda4684e6343", "ccea9fd7-d822-45a8-be4d-48897d71855f")
***IFI_04_2_Ann=IFBLANK(SCORE("PRI reporting framework 2013/2014: (1.11.1.5.1.2.1.1.1) . . . . . . . . . Q. Annually or more frequently", "e0851e70a446413880dee8d8b7f29c4b", "ccea9fd7-d822-45a8-be4d-48897d71855f"),0)
***IFI_04_2_2yrs=IFBLANK(SCORE("PRI reporting framework 2013/2014: (1.11.1.5.1.2.1.1.2) . . . . . . . . . Q. Every two years or less", "9da41b846f0d46ffa9193aab16307ea9", "ccea9fd7-d822-45a8-be4d-48897d71855f"),0)
***IFI_04_2_adhoc=IFBLANK(SCORE("PRI reporting framework 2013/2014: (1.11.1.5.1.2.1.1.3) . . . . . . . . . Q. Ad-hoc, specify", "3d86111a911f471eac9d1edce15dbbf8", "ccea9fd7-d822-45a8-be4d-48897d71855f"),0)
***IFI_04_2_N=IFBLANK(SCORE("PRI reporting framework 2013/2014: (1.11.1.5.1.2.2) . . . . . . . Q. No", "add1e4f0352d48efaef3e93e72d4fe87", "ccea9fd7-d822-45a8-be4d-48897d71855f"),0)
***IFI_04_SCORE=VALUE(IFI_04_2_Ann)+VALUE(IFI_04_2_2yrs)+VALUE(IFI_04_2_adhoc)+VALUE(IFI_04_2_N)
***IFI_05_1=SCORE("PRI reporting framework 2013/2014: (1.11.1.5.2.1) . . . . . . Q05.1. Indicate if you require your investment managers to provide you with information in line with established industry standards.", "1dc7e2c411f5486abce6ab93401c9433", "ccea9fd7-d822-45a8-be4d-48897d71855f")
***IFI_05_1_Y=IFBLANK(SCORE("PRI reporting framework 2013/2014: (1.11.1.5.2.1.1) . . . . . . . Q. Yes", "17c44589b7df44119a3df56f19bb484f", "ccea9fd7-d822-45a8-be4d-48897d71855f"),0)
***IFI_05_1_N=IFBLANK(SCORE("PRI reporting framework 2013/2014: (1.11.1.5.2.1.2) . . . . . . . Q. No", "d63bfad2659b45d696af1c688c143cd2", "ccea9fd7-d822-45a8-be4d-48897d71855f"),0)
***IFI_05_SCORE=VALUE(
IF((IFI_05_1_Y=100),3,0))
***IFI_06_1=SCORE("PRI reporting framework 2013/2014: (1.11.1.6.1.2) . . . . . . Q06.1. Indicate if your organisation proactively discloses any information about your approach to responsible investment in inclusive finance.", "6d1dfdf645d14913b7b8aff30b29b572", "ccea9fd7-d822-45a8-be4d-48897d71855f")
***IFI_06_1_YP=SCORE("PRI reporting framework 2013/2014: (1.11.1.6.1.2.1) . . . . . . . Q. Yes, we disclose publicly", "905b575ab78b4f6fb37eba6ed1781a14", "ccea9fd7-d822-45a8-be4d-48897d71855f")
***IFI_06_1_CB=SCORE("PRI reporting framework 2013/2014: (1.11.1.6.1.2.2) . . . . . . . Q. Yes, we disclose  to clients/beneficiaries only", "d3f6360e494749b989aeb78a493af825", "ccea9fd7-d822-45a8-be4d-48897d71855f")
***IFI_06_1_N=SCORE("PRI reporting framework 2013/2014: (1.11.1.6.1.2.3) . . . . . . . Q. No", "d430b61fa1834732a37758c15d0d347d", "ccea9fd7-d822-45a8-be4d-48897d71855f")
***IFI_06_SCORE=VALUE(IFI_06_1_YP)+VALUE(IFI_06_1_CB)+VALUE(IFI_06_1_N)
***IFI_Total=VALUE(IFI_02_SCORE)+VALUE(IFI_03_SCORE)+VALUE(IFI_04_SCORE)+VALUE(IFI_05_SCORE)+VALUE(IFI_06_SCORE)
***IFI_Percent=DIVIDE(IFI_Total,15)
***IFI_Level=TEXT(
IF((IF_External)="0","NA", 
IF((IF_External="<10%") AND (OO_11_IFI<>"")AND(OO_12_IFI=""),"NR",
IF((OO_12_IFI=""),"E",
IF((IFI_Percent)=0, "E",
IF((IFI_Percent)<=0.25, "D",
IF((IFI_Percent)<=0.50, "C",
IF((IFI_Percent)<=0.75, "B",
IF((IFI_Percent)<0.95, "A",
IF((IFI_Percent)>=0.95, "A+"
))))))))))
***IFI_Sel_Section=VALUE(IFI_02_SCORE)
***IFI_Con_Section=VALUE(IFI_03_SCORE)
***IFI_Mon_Section=DIVIDE((VALUE(IFI_04_SCORE)+VALUE(IFI_05_SCORE)),2)
***IFI_Disc_Section=VALUE(IFI_06_SCORE)
***IFI_COUNT_E=SUM(IF(IFI_Level="E",1,0))
***IFI_COUNT_D=SUM(IF(IFI_Level="D",1,0))
***IFI_COUNT_C=SUM(IF(IFI_Level="C",1,0))
***IFI_COUNT_B=SUM(IF(IFI_Level="B",1,0))
***IFI_COUNT_A=SUM(IF(IFI_Level="A",1,0))
***IFI_COUNT_A+=SUM(IF(IFI_Level="A+",1,0))
***IFI_COUNT_E_IM=SUM(IF((IFI_Level="E")AND(Type="IM"),1,0))
***IFI_COUNT_D_IM=SUM(IF((IFI_Level="D")AND(Type="IM"),1,0))
***IFI_COUNT_C_IM=SUM(IF((IFI_Level="C")AND(Type="IM"),1,0))
***IFI_COUNT_B_IM=SUM(IF((IFI_Level="B")AND(Type="IM"),1,0))
***IFI_COUNT_A_IM=SUM(IF((IFI_Level="A")AND(Type="IM"),1,0))
***IFI_COUNT_A+_IM=SUM(IF((IFI_Level="A+")AND(Type="IM"),1,0))
***IFI_COUNT_E_AO=SUM(IF((IFI_Level="E")AND(Type="AO"),1,0))
***IFI_COUNT_D_AO=SUM(IF((IFI_Level="D")AND(Type="AO"),1,0))
***IFI_COUNT_C_AO=SUM(IF((IFI_Level="C")AND(Type="AO"),1,0))
***IFI_COUNT_B_AO=SUM(IF((IFI_Level="B")AND(Type="AO"),1,0))
***IFI_COUNT_A_AO=SUM(IF((IFI_Level="A")AND(Type="AO"),1,0))
***IFI_COUNT_A+_AO=SUM(IF((IFI_Level="A+")AND(Type="AO"),1,0))
***IFI_COUNT_E_IM_Africa=SUM(IF((IFI_Level="E")AND(Region="Africa")AND(Type="IM"),1,0,))
***IFI_COUNT_D_IM_Africa=SUM(IF((IFI_Level="D")AND(Region="Africa")AND(Type="IM"),1,0,))
***IFI_COUNT_C_IM_Africa=SUM(IF((IFI_Level="C")AND(Region="Africa")AND(Type="IM"),1,0,))
***IFI_COUNT_B_IM_Africa=SUM(IF((IFI_Level="B")AND(Region="Africa")AND(Type="IM"),1,0,))
***IFI_COUNT_A_IM_Africa=SUM(IF((IFI_Level="A")AND(Region="Africa")AND(Type="IM"),1,0,))
***IFI_COUNT_A+_IM_Africa=SUM(IF((IFI_Level="A+")AND(Region="Africa")AND(Type="IM"),1,0,))
***IFI_COUNT_E_IM_Asia=SUM(IF((IFI_Level="E")AND(Region="Asia")AND(Type="IM"),1,0,))
***IFI_COUNT_D_IM_Asia=SUM(IF((IFI_Level="D")AND(Region="Asia")AND(Type="IM"),1,0,))
***IFI_COUNT_C_IM_Asia=SUM(IF((IFI_Level="C")AND(Region="Asia")AND(Type="IM"),1,0,))
***IFI_COUNT_B_IM_Asia=SUM(IF((IFI_Level="B")AND(Region="Asia")AND(Type="IM"),1,0,))
***IFI_COUNT_A_IM_Asia=SUM(IF((IFI_Level="A")AND(Region="Asia")AND(Type="IM"),1,0,))
***IFI_COUNT_A+_IM_Asia=SUM(IF((IFI_Level="A+")AND(Region="Asia")AND(Type="IM"),1,0,))
***IFI_COUNT_E_IM_Europe=SUM(IF((IFI_Level="E")AND(Region="Europe")AND(Type="IM"),1,0,))
***IFI_COUNT_D_IM_Europe=SUM(IF((IFI_Level="D")AND(Region="Europe")AND(Type="IM"),1,0,))
***IFI_COUNT_C_IM_Europe=SUM(IF((IFI_Level="C")AND(Region="Europe")AND(Type="IM"),1,0,))
***IFI_COUNT_B_IM_Europe=SUM(IF((IFI_Level="B")AND(Region="Europe")AND(Type="IM"),1,0,))
***IFI_COUNT_A_IM_Europe=SUM(IF((IFI_Level="A")AND(Region="Europe")AND(Type="IM"),1,0,))
***IFI_COUNT_A+_IM_Europe=SUM(IF((IFI_Level="A+")AND(Region="Europe")AND(Type="IM"),1,0,))
***IFI_COUNT_E_IM_Latin America=SUM(IF((IFI_Level="E")AND(Region="Latin America")AND(Type="IM"),1,0,))
***IFI_COUNT_D_IM_Latin America=SUM(IF((IFI_Level="D")AND(Region="Latin America")AND(Type="IM"),1,0,))
***IFI_COUNT_C_IM_Latin America=SUM(IF((IFI_Level="C")AND(Region="Latin America")AND(Type="IM"),1,0,))
***IFI_COUNT_B_IM_Latin America=SUM(IF((IFI_Level="B")AND(Region="Latin America")AND(Type="IM"),1,0,))
***IFI_COUNT_A_IM_Latin America=SUM(IF((IFI_Level="A")AND(Region="Latin America")AND(Type="IM"),1,0,))
***IFI_COUNT_A+_IM_Latin America=SUM(IF((IFI_Level="A+")AND(Region="Latin America")AND(Type="IM"),1,0,))
***IFI_COUNT_E_IM_Middle East=SUM(IF((IFI_Level="E")AND(Region="Middle East")AND(Type="IM"),1,0,))
***IFI_COUNT_D_IM_Middle East=SUM(IF((IFI_Level="D")AND(Region="Middle East")AND(Type="IM"),1,0,))
***IFI_COUNT_C_IM_Middle East=SUM(IF((IFI_Level="C")AND(Region="Middle East")AND(Type="IM"),1,0,))
***IFI_COUNT_B_IM_Middle East=SUM(IF((IFI_Level="B")AND(Region="Middle East")AND(Type="IM"),1,0,))
***IFI_COUNT_A_IM_Middle East=SUM(IF((IFI_Level="A")AND(Region="Middle East")AND(Type="IM"),1,0,))
***IFI_COUNT_A+_IM_Middle East=SUM(IF((IFI_Level="A+")AND(Region="Middle East")AND(Type="IM"),1,0,))
***IFI_COUNT_E_IM_North America=SUM(IF((IFI_Level="E")AND(Region="North America")AND(Type="IM"),1,0,))
***IFI_COUNT_D_IM_North America=SUM(IF((IFI_Level="D")AND(Region="North America")AND(Type="IM"),1,0,))
***IFI_COUNT_C_IM_North America=SUM(IF((IFI_Level="C")AND(Region="North America")AND(Type="IM"),1,0,))
***IFI_COUNT_B_IM_North America=SUM(IF((IFI_Level="B")AND(Region="North America")AND(Type="IM"),1,0,))
***IFI_COUNT_A_IM_North America=SUM(IF((IFI_Level="A")AND(Region="North America")AND(Type="IM"),1,0,))
***IFI_COUNT_A+_IM_North America=SUM(IF((IFI_Level="A+")AND(Region="North America")AND(Type="IM"),1,0,))
***IFI_COUNT_E_IM_Oceania=SUM(IF((IFI_Level="E")AND(Region="Oceania")AND(Type="IM"),1,0,))
***IFI_COUNT_D_IM_Oceania=SUM(IF((IFI_Level="D")AND(Region="Oceania")AND(Type="IM"),1,0,))
***IFI_COUNT_C_IM_Oceania=SUM(IF((IFI_Level="C")AND(Region="Oceania")AND(Type="IM"),1,0,))
***IFI_COUNT_B_IM_Oceania=SUM(IF((IFI_Level="B")AND(Region="Oceania")AND(Type="IM"),1,0,))
***IFI_COUNT_A_IM_Oceania=SUM(IF((IFI_Level="A")AND(Region="Oceania")AND(Type="IM"),1,0,))
***IFI_COUNT_A+_IM_Oceania=SUM(IF((IFI_Level="A+")AND(Region="Oceania")AND(Type="IM"),1,0,))
***IFI_COUNT_E_AO_Africa=SUM(IF((IFI_Level="E")AND(Region="Africa")AND(Type="AO"),1,0,))
***IFI_COUNT_D_AO_Africa=SUM(IF((IFI_Level="D")AND(Region="Africa")AND(Type="AO"),1,0,))
***IFI_COUNT_C_AO_Africa=SUM(IF((IFI_Level="C")AND(Region="Africa")AND(Type="AO"),1,0,))
***IFI_COUNT_B_AO_Africa=SUM(IF((IFI_Level="B")AND(Region="Africa")AND(Type="AO"),1,0,))
***IFI_COUNT_A_AO_Africa=SUM(IF((IFI_Level="A")AND(Region="Africa")AND(Type="AO"),1,0,))
***IFI_COUNT_A+_AO_Africa=SUM(IF((IFI_Level="A+")AND(Region="Africa")AND(Type="AO"),1,0,))
***IFI_COUNT_E_AO_Asia=SUM(IF((IFI_Level="E")AND(Region="Asia")AND(Type="AO"),1,0,))
***IFI_COUNT_D_AO_Asia=SUM(IF((IFI_Level="D")AND(Region="Asia")AND(Type="AO"),1,0,))
***IFI_COUNT_C_AO_Asia=SUM(IF((IFI_Level="C")AND(Region="Asia")AND(Type="AO"),1,0,))
***IFI_COUNT_B_AO_Asia=SUM(IF((IFI_Level="B")AND(Region="Asia")AND(Type="AO"),1,0,))
***IFI_COUNT_A_AO_Asia=SUM(IF((IFI_Level="A")AND(Region="Asia")AND(Type="AO"),1,0,))
***IFI_COUNT_A+_AO_Asia=SUM(IF((IFI_Level="A+")AND(Region="Asia")AND(Type="AO"),1,0,))
***IFI_COUNT_E_AO_Europe=SUM(IF((IFI_Level="E")AND(Region="Europe")AND(Type="AO"),1,0,))
***IFI_COUNT_D_AO_Europe=SUM(IF((IFI_Level="D")AND(Region="Europe")AND(Type="AO"),1,0,))
***IFI_COUNT_C_AO_Europe=SUM(IF((IFI_Level="C")AND(Region="Europe")AND(Type="AO"),1,0,))
***IFI_COUNT_B_AO_Europe=SUM(IF((IFI_Level="B")AND(Region="Europe")AND(Type="AO"),1,0,))
***IFI_COUNT_A_AO_Europe=SUM(IF((IFI_Level="A")AND(Region="Europe")AND(Type="AO"),1,0,))
***IFI_COUNT_A+_AO_Europe=SUM(IF((IFI_Level="A+")AND(Region="Europe")AND(Type="AO"),1,0,))
***IFI_COUNT_E_AO_Latin America=SUM(IF((IFI_Level="E")AND(Region="Latin America")AND(Type="AO"),1,0,))
***IFI_COUNT_D_AO_Latin America=SUM(IF((IFI_Level="D")AND(Region="Latin America")AND(Type="AO"),1,0,))
***IFI_COUNT_C_AO_Latin America=SUM(IF((IFI_Level="C")AND(Region="Latin America")AND(Type="AO"),1,0,))
***IFI_COUNT_B_AO_Latin America=SUM(IF((IFI_Level="B")AND(Region="Latin America")AND(Type="AO"),1,0,))
***IFI_COUNT_A_AO_Latin America=SUM(IF((IFI_Level="A")AND(Region="Latin America")AND(Type="AO"),1,0,))
***IFI_COUNT_A+_AO_Latin America=SUM(IF((IFI_Level="A+")AND(Region="Latin America")AND(Type="AO"),1,0,))
***IFI_COUNT_E_AO_Middle East=SUM(IF((IFI_Level="E")AND(Region="Middle East")AND(Type="AO"),1,0,))
***IFI_COUNT_D_AO_Middle East=SUM(IF((IFI_Level="D")AND(Region="Middle East")AND(Type="AO"),1,0,))
***IFI_COUNT_C_AO_Middle East=SUM(IF((IFI_Level="C")AND(Region="Middle East")AND(Type="AO"),1,0,))
***IFI_COUNT_B_AO_Middle East=SUM(IF((IFI_Level="B")AND(Region="Middle East")AND(Type="AO"),1,0,))
***IFI_COUNT_A_AO_Middle East=SUM(IF((IFI_Level="A")AND(Region="Middle East")AND(Type="AO"),1,0,))
***IFI_COUNT_A+_AO_Middle East=SUM(IF((IFI_Level="A+")AND(Region="Middle East")AND(Type="AO"),1,0,))
***IFI_COUNT_E_AO_North America=SUM(IF((IFI_Level="E")AND(Region="North America")AND(Type="AO"),1,0,))
***IFI_COUNT_D_AO_North America=SUM(IF((IFI_Level="D")AND(Region="North America")AND(Type="AO"),1,0,))
***IFI_COUNT_C_AO_North America=SUM(IF((IFI_Level="C")AND(Region="North America")AND(Type="AO"),1,0,))
***IFI_COUNT_B_AO_North America=SUM(IF((IFI_Level="B")AND(Region="North America")AND(Type="AO"),1,0,))
***IFI_COUNT_A_AO_North America=SUM(IF((IFI_Level="A")AND(Region="North America")AND(Type="AO"),1,0,))
***IFI_COUNT_A+_AO_North America=SUM(IF((IFI_Level="A+")AND(Region="North America")AND(Type="AO"),1,0,))
***IFI_COUNT_E_AO_Oceania=SUM(IF((IFI_Level="E")AND(Region="Oceania")AND(Type="AO"),1,0,))
***IFI_COUNT_D_AO_Oceania=SUM(IF((IFI_Level="D")AND(Region="Oceania")AND(Type="AO"),1,0,))
***IFI_COUNT_C_AO_Oceania=SUM(IF((IFI_Level="C")AND(Region="Oceania")AND(Type="AO"),1,0,))
***IFI_COUNT_B_AO_Oceania=SUM(IF((IFI_Level="B")AND(Region="Oceania")AND(Type="AO"),1,0,))
***IFI_COUNT_A_AO_Oceania=SUM(IF((IFI_Level="A")AND(Region="Oceania")AND(Type="AO"),1,0,))
***IFI_COUNT_A+_AO_Oceania=SUM(IF((IFI_Level="A+")AND(Region="Oceania")AND(Type="AO"),1,0,))
***IFI_COUNT_E_IM_0 - 0.1=SUM(IF((IFI_Level="E")AND(Size="0 - 0.1")AND(Type="IM"),1,0,))
***IFI_COUNT_D_IM_0 - 0.1=SUM(IF((IFI_Level="D")AND(Size="0 - 0.1")AND(Type="IM"),1,0,))
***IFI_COUNT_C_IM_0 - 0.1=SUM(IF((IFI_Level="C")AND(Size="0 - 0.1")AND(Type="IM"),1,0,))
***IFI_COUNT_B_IM_0 - 0.1=SUM(IF((IFI_Level="B")AND(Size="0 - 0.1")AND(Type="IM"),1,0,))
***IFI_COUNT_A_IM_0 - 0.1=SUM(IF((IFI_Level="A")AND(Size="0 - 0.1")AND(Type="IM"),1,0,))
***IFI_COUNT_A+_IM_0 - 0.1=SUM(IF((IFI_Level="A+")AND(Size="0 - 0.1")AND(Type="IM"),1,0,))
***IFI_COUNT_E_IM_0.1 - 0.99=SUM(IF((IFI_Level="E")AND(Size="0.1 - 0.99")AND(Type="IM"),1,0,))
***IFI_COUNT_D_IM_0.1 - 0.99=SUM(IF((IFI_Level="D")AND(Size="0.1 - 0.99")AND(Type="IM"),1,0,))
***IFI_COUNT_C_IM_0.1 - 0.99=SUM(IF((IFI_Level="C")AND(Size="0.1 - 0.99")AND(Type="IM"),1,0,))
***IFI_COUNT_B_IM_0.1 - 0.99=SUM(IF((IFI_Level="B")AND(Size="0.1 - 0.99")AND(Type="IM"),1,0,))
***IFI_COUNT_A_IM_0.1 - 0.99=SUM(IF((IFI_Level="A")AND(Size="0.1 - 0.99")AND(Type="IM"),1,0,))
***IFI_COUNT_A+_IM_0.1 - 0.99=SUM(IF((IFI_Level="A+")AND(Size="0.1 - 0.99")AND(Type="IM"),1,0,))
***IFI_COUNT_E_IM_1 - 4.99=SUM(IF((IFI_Level="E")AND(Size="1 - 4.99")AND(Type="IM"),1,0,))
***IFI_COUNT_D_IM_1 - 4.99=SUM(IF((IFI_Level="D")AND(Size="1 - 4.99")AND(Type="IM"),1,0,))
***IFI_COUNT_C_IM_1 - 4.99=SUM(IF((IFI_Level="C")AND(Size="1 - 4.99")AND(Type="IM"),1,0,))
***IFI_COUNT_B_IM_1 - 4.99=SUM(IF((IFI_Level="B")AND(Size="1 - 4.99")AND(Type="IM"),1,0,))
***IFI_COUNT_A_IM_1 - 4.99=SUM(IF((IFI_Level="A")AND(Size="1 - 4.99")AND(Type="IM"),1,0,))
***IFI_COUNT_A+_IM_1 - 4.99=SUM(IF((IFI_Level="A+")AND(Size="1 - 4.99")AND(Type="IM"),1,0,))
***IFI_COUNT_E_IM_5 - 9.99=SUM(IF((IFI_Level="E")AND(Size="5 - 9.99")AND(Type="IM"),1,0,))
***IFI_COUNT_D_IM_5 - 9.99=SUM(IF((IFI_Level="D")AND(Size="5 - 9.99")AND(Type="IM"),1,0,))
***IFI_COUNT_C_IM_5 - 9.99=SUM(IF((IFI_Level="C")AND(Size="5 - 9.99")AND(Type="IM"),1,0,))
***IFI_COUNT_B_IM_5 - 9.99=SUM(IF((IFI_Level="B")AND(Size="5 - 9.99")AND(Type="IM"),1,0,))
***IFI_COUNT_A_IM_5 - 9.99=SUM(IF((IFI_Level="A")AND(Size="5 - 9.99")AND(Type="IM"),1,0,))
***IFI_COUNT_A+_IM_5 - 9.99=SUM(IF((IFI_Level="A+")AND(Size="5 - 9.99")AND(Type="IM"),1,0,))
***IFI_COUNT_E_IM_>10=SUM(IF((IFI_Level="E")AND(Size="> 10")AND(Type="IM"),1,0,))
***IFI_COUNT_D_IM_>10=SUM(IF((IFI_Level="D")AND(Size="> 10")AND(Type="IM"),1,0,))
***IFI_COUNT_C_IM_>10=SUM(IF((IFI_Level="C")AND(Size="> 10")AND(Type="IM"),1,0,))
***IFI_COUNT_B_IM_>10=SUM(IF((IFI_Level="B")AND(Size="> 10")AND(Type="IM"),1,0,))
***IFI_COUNT_A_IM_>10=SUM(IF((IFI_Level="A")AND(Size="> 10")AND(Type="IM"),1,0,))
***IFI_COUNT_A+_IM_>10=SUM(IF((IFI_Level="A+")AND(Size="> 10")AND(Type="IM"),1,0,))
***IFI_COUNT_E_IM_10 - 29.99=SUM(IF((IFI_Level="E")AND(Size="10 - 29.99")AND(Type="IM"),1,0,))
***IFI_COUNT_D_IM_10 - 29.99=SUM(IF((IFI_Level="D")AND(Size="10 - 29.99")AND(Type="IM"),1,0,))
***IFI_COUNT_C_IM_10 - 29.99=SUM(IF((IFI_Level="C")AND(Size="10 - 29.99")AND(Type="IM"),1,0,))
***IFI_COUNT_B_IM_10 - 29.99=SUM(IF((IFI_Level="B")AND(Size="10 - 29.99")AND(Type="IM"),1,0,))
***IFI_COUNT_A_IM_10 - 29.99=SUM(IF((IFI_Level="A")AND(Size="10 - 29.99")AND(Type="IM"),1,0,))
***IFI_COUNT_A+_IM_10 - 29.99=SUM(IF((IFI_Level="A+")AND(Size="10 - 29.99")AND(Type="IM"),1,0,))
***IFI_COUNT_E_IM_30 - 50=SUM(IF((IFI_Level="E")AND(Size="30 - 50")AND(Type="IM"),1,0,))
***IFI_COUNT_D_IM_30 - 50=SUM(IF((IFI_Level="D")AND(Size="30 - 50")AND(Type="IM"),1,0,))
***IFI_COUNT_C_IM_30 - 50=SUM(IF((IFI_Level="C")AND(Size="30 - 50")AND(Type="IM"),1,0,))
***IFI_COUNT_B_IM_30 - 50=SUM(IF((IFI_Level="B")AND(Size="30 - 50")AND(Type="IM"),1,0,))
***IFI_COUNT_A_IM_30 - 50=SUM(IF((IFI_Level="A")AND(Size="30 - 50")AND(Type="IM"),1,0,))
***IFI_COUNT_A+_IM_30 - 50=SUM(IF((IFI_Level="A+")AND(Size="30 - 50")AND(Type="IM"),1,0,))
***IFI_COUNT_E_IM_>50=SUM(IF((IFI_Level="E")AND(Size="> 50")AND(Type="IM"),1,0,))
***IFI_COUNT_D_IM_>50=SUM(IF((IFI_Level="D")AND(Size="> 50")AND(Type="IM"),1,0,))
***IFI_COUNT_C_IM_>50=SUM(IF((IFI_Level="C")AND(Size="> 50")AND(Type="IM"),1,0,))
***IFI_COUNT_B_IM_>50=SUM(IF((IFI_Level="B")AND(Size="> 50")AND(Type="IM"),1,0,))
***IFI_COUNT_A_IM_>50=SUM(IF((IFI_Level="A")AND(Size="> 50")AND(Type="IM"),1,0,))
***IFI_COUNT_A+_IM_>50=SUM(IF((IFI_Level="A+")AND(Size="> 50")AND(Type="IM"),1,0,))
***IFI_COUNT_E_AO_0 - 0.1=SUM(IF((IFI_Level="E")AND(Size="0 - 0.1")AND(Type="AO"),1,0,))
***IFI_COUNT_D_AO_0 - 0.1=SUM(IF((IFI_Level="D")AND(Size="0 - 0.1")AND(Type="AO"),1,0,))
***IFI_COUNT_C_AO_0 - 0.1=SUM(IF((IFI_Level="C")AND(Size="0 - 0.1")AND(Type="AO"),1,0,))
***IFI_COUNT_B_AO_0 - 0.1=SUM(IF((IFI_Level="B")AND(Size="0 - 0.1")AND(Type="AO"),1,0,))
***IFI_COUNT_A_AO_0 - 0.1=SUM(IF((IFI_Level="A")AND(Size="0 - 0.1")AND(Type="AO"),1,0,))
***IFI_COUNT_A+_AO_0 - 0.1=SUM(IF((IFI_Level="A+")AND(Size="0 - 0.1")AND(Type="AO"),1,0,))
***IFI_COUNT_E_AO_0.1 - 0.99=SUM(IF((IFI_Level="E")AND(Size="0.1 - 0.99")AND(Type="AO"),1,0,))
***IFI_COUNT_D_AO_0.1 - 0.99=SUM(IF((IFI_Level="D")AND(Size="0.1 - 0.99")AND(Type="AO"),1,0,))
***IFI_COUNT_C_AO_0.1 - 0.99=SUM(IF((IFI_Level="C")AND(Size="0.1 - 0.99")AND(Type="AO"),1,0,))
***IFI_COUNT_B_AO_0.1 - 0.99=SUM(IF((IFI_Level="B")AND(Size="0.1 - 0.99")AND(Type="AO"),1,0,))
***IFI_COUNT_A_AO_0.1 - 0.99=SUM(IF((IFI_Level="A")AND(Size="0.1 - 0.99")AND(Type="AO"),1,0,))
***IFI_COUNT_A+_AO_0.1 - 0.99=SUM(IF((IFI_Level="A+")AND(Size="0.1 - 0.99")AND(Type="AO"),1,0,))
***IFI_COUNT_E_AO_1 - 4.99=SUM(IF((IFI_Level="E")AND(Size="1 - 4.99")AND(Type="AO"),1,0,))
***IFI_COUNT_D_AO_1 - 4.99=SUM(IF((IFI_Level="D")AND(Size="1 - 4.99")AND(Type="AO"),1,0,))
***IFI_COUNT_C_AO_1 - 4.99=SUM(IF((IFI_Level="C")AND(Size="1 - 4.99")AND(Type="AO"),1,0,))
***IFI_COUNT_B_AO_1 - 4.99=SUM(IF((IFI_Level="B")AND(Size="1 - 4.99")AND(Type="AO"),1,0,))
***IFI_COUNT_A_AO_1 - 4.99=SUM(IF((IFI_Level="A")AND(Size="1 - 4.99")AND(Type="AO"),1,0,))
***IFI_COUNT_A+_AO_1 - 4.99=SUM(IF((IFI_Level="A+")AND(Size="1 - 4.99")AND(Type="AO"),1,0,))
***IFI_COUNT_E_AO_5 - 9.99=SUM(IF((IFI_Level="E")AND(Size="5 - 9.99")AND(Type="AO"),1,0,))
***IFI_COUNT_D_AO_5 - 9.99=SUM(IF((IFI_Level="D")AND(Size="5 - 9.99")AND(Type="AO"),1,0,))
***IFI_COUNT_C_AO_5 - 9.99=SUM(IF((IFI_Level="C")AND(Size="5 - 9.99")AND(Type="AO"),1,0,))
***IFI_COUNT_B_AO_5 - 9.99=SUM(IF((IFI_Level="B")AND(Size="5 - 9.99")AND(Type="AO"),1,0,))
***IFI_COUNT_A_AO_5 - 9.99=SUM(IF((IFI_Level="A")AND(Size="5 - 9.99")AND(Type="AO"),1,0,))
***IFI_COUNT_A+_AO_5 - 9.99=SUM(IF((IFI_Level="A+")AND(Size="5 - 9.99")AND(Type="AO"),1,0,))
***IFI_COUNT_E_AO_>10=SUM(IF((IFI_Level="E")AND(Size="> 10")AND(Type="AO"),1,0,))
***IFI_COUNT_D_AO_>10=SUM(IF((IFI_Level="D")AND(Size="> 10")AND(Type="AO"),1,0,))
***IFI_COUNT_C_AO_>10=SUM(IF((IFI_Level="C")AND(Size="> 10")AND(Type="AO"),1,0,))
***IFI_COUNT_B_AO_>10=SUM(IF((IFI_Level="B")AND(Size="> 10")AND(Type="AO"),1,0,))
***IFI_COUNT_A_AO_>10=SUM(IF((IFI_Level="A")AND(Size="> 10")AND(Type="AO"),1,0,))
***IFI_COUNT_A+_AO_>10=SUM(IF((IFI_Level="A+")AND(Size="> 10")AND(Type="AO"),1,0,))
***IFI_COUNT_E_AO_2006=SUM(IF((IFI_Level="E")AND(Signed_PRI="2006")AND(Type="AO"),1,0,))
***IFI_COUNT_D_AO_2006=SUM(IF((IFI_Level="D")AND(Signed_PRI="2006")AND(Type="AO"),1,0,))
***IFI_COUNT_C_AO_2006=SUM(IF((IFI_Level="C")AND(Signed_PRI="2006")AND(Type="AO"),1,0,))
***IFI_COUNT_B_AO_2006=SUM(IF((IFI_Level="B")AND(Signed_PRI="2006")AND(Type="AO"),1,0,))
***IFI_COUNT_A_AO_2006=SUM(IF((IFI_Level="A")AND(Signed_PRI="2006")AND(Type="AO"),1,0,))
***IFI_COUNT_A+_AO_2006=SUM(IF((IFI_Level="A+")AND(Signed_PRI="2006")AND(Type="AO"),1,0,))
***IFI_COUNT_E_AO_2007=SUM(IF((IFI_Level="E")AND(Signed_PRI="2007")AND(Type="AO"),1,0,))
***IFI_COUNT_D_AO_2007=SUM(IF((IFI_Level="D")AND(Signed_PRI="2007")AND(Type="AO"),1,0,))
***IFI_COUNT_C_AO_2007=SUM(IF((IFI_Level="C")AND(Signed_PRI="2007")AND(Type="AO"),1,0,))
***IFI_COUNT_B_AO_2007=SUM(IF((IFI_Level="B")AND(Signed_PRI="2007")AND(Type="AO"),1,0,))
***IFI_COUNT_A_AO_2007=SUM(IF((IFI_Level="A")AND(Signed_PRI="2007")AND(Type="AO"),1,0,))
***IFI_COUNT_A+_AO_2007=SUM(IF((IFI_Level="A+")AND(Signed_PRI="2007")AND(Type="AO"),1,0,))
***IFI_COUNT_E_AO_2008=SUM(IF((IFI_Level="E")AND(Signed_PRI="2008")AND(Type="AO"),1,0,))
***IFI_COUNT_D_AO_2008=SUM(IF((IFI_Level="D")AND(Signed_PRI="2008")AND(Type="AO"),1,0,))
***IFI_COUNT_C_AO_2008=SUM(IF((IFI_Level="C")AND(Signed_PRI="2008")AND(Type="AO"),1,0,))
***IFI_COUNT_B_AO_2008=SUM(IF((IFI_Level="B")AND(Signed_PRI="2008")AND(Type="AO"),1,0,))
***IFI_COUNT_A_AO_2008=SUM(IF((IFI_Level="A")AND(Signed_PRI="2008")AND(Type="AO"),1,0,))
***IFI_COUNT_A+_AO_2008=SUM(IF((IFI_Level="A+")AND(Signed_PRI="2008")AND(Type="AO"),1,0,))
***IFI_COUNT_E_AO_2009=SUM(IF((IFI_Level="E")AND(Signed_PRI="2009")AND(Type="AO"),1,0,))
***IFI_COUNT_D_AO_2009=SUM(IF((IFI_Level="D")AND(Signed_PRI="2009")AND(Type="AO"),1,0,))
***IFI_COUNT_C_AO_2009=SUM(IF((IFI_Level="C")AND(Signed_PRI="2009")AND(Type="AO"),1,0,))
***IFI_COUNT_B_AO_2009=SUM(IF((IFI_Level="B")AND(Signed_PRI="2009")AND(Type="AO"),1,0,))
***IFI_COUNT_A_AO_2009=SUM(IF((IFI_Level="A")AND(Signed_PRI="2009")AND(Type="AO"),1,0,))
***IFI_COUNT_A+_AO_2009=SUM(IF((IFI_Level="A+")AND(Signed_PRI="2009")AND(Type="AO"),1,0,))
***IFI_COUNT_E_AO_2010=SUM(IF((IFI_Level="E")AND(Signed_PRI="2010")AND(Type="AO"),1,0,))
***IFI_COUNT_D_AO_2010=SUM(IF((IFI_Level="D")AND(Signed_PRI="2010")AND(Type="AO"),1,0,))
***IFI_COUNT_C_AO_2010=SUM(IF((IFI_Level="C")AND(Signed_PRI="2010")AND(Type="AO"),1,0,))
***IFI_COUNT_B_AO_2010=SUM(IF((IFI_Level="B")AND(Signed_PRI="2010")AND(Type="AO"),1,0,))
***IFI_COUNT_A_AO_2010=SUM(IF((IFI_Level="A")AND(Signed_PRI="2010")AND(Type="AO"),1,0,))
***IFI_COUNT_A+_AO_2010=SUM(IF((IFI_Level="A+")AND(Signed_PRI="2010")AND(Type="AO"),1,0,))
***IFI_COUNT_E_AO_2011=SUM(IF((IFI_Level="E")AND(Signed_PRI="2011")AND(Type="AO"),1,0,))
***IFI_COUNT_D_AO_2011=SUM(IF((IFI_Level="D")AND(Signed_PRI="2011")AND(Type="AO"),1,0,))
***IFI_COUNT_C_AO_2011=SUM(IF((IFI_Level="C")AND(Signed_PRI="2011")AND(Type="AO"),1,0,))
***IFI_COUNT_B_AO_2011=SUM(IF((IFI_Level="B")AND(Signed_PRI="2011")AND(Type="AO"),1,0,))
***IFI_COUNT_A_AO_2011=SUM(IF((IFI_Level="A")AND(Signed_PRI="2011")AND(Type="AO"),1,0,))
***IFI_COUNT_A+_AO_2011=SUM(IF((IFI_Level="A+")AND(Signed_PRI="2011")AND(Type="AO"),1,0,))
***IFI_COUNT_E_AO_2012=SUM(IF((IFI_Level="E")AND(Signed_PRI="2012")AND(Type="AO"),1,0,))
***IFI_COUNT_D_AO_2012=SUM(IF((IFI_Level="D")AND(Signed_PRI="2012")AND(Type="AO"),1,0,))
***IFI_COUNT_C_AO_2012=SUM(IF((IFI_Level="C")AND(Signed_PRI="2012")AND(Type="AO"),1,0,))
***IFI_COUNT_B_AO_2012=SUM(IF((IFI_Level="B")AND(Signed_PRI="2012")AND(Type="AO"),1,0,))
***IFI_COUNT_A_AO_2012=SUM(IF((IFI_Level="A")AND(Signed_PRI="2012")AND(Type="AO"),1,0,))
***IFI_COUNT_A+_AO_2012=SUM(IF((IFI_Level="A+")AND(Signed_PRI="2012")AND(Type="AO"),1,0,))
***IFI_COUNT_E_AO_2013=SUM(IF((IFI_Level="E")AND(Signed_PRI="2013")AND(Type="AO"),1,0,))
***IFI_COUNT_D_AO_2013=SUM(IF((IFI_Level="D")AND(Signed_PRI="2013")AND(Type="AO"),1,0,))
***IFI_COUNT_C_AO_2013=SUM(IF((IFI_Level="C")AND(Signed_PRI="2013")AND(Type="AO"),1,0,))
***IFI_COUNT_B_AO_2013=SUM(IF((IFI_Level="B")AND(Signed_PRI="2013")AND(Type="AO"),1,0,))
***IFI_COUNT_A_AO_2013=SUM(IF((IFI_Level="A")AND(Signed_PRI="2013")AND(Type="AO"),1,0,))
***IFI_COUNT_A+_AO_2013=SUM(IF((IFI_Level="A+")AND(Signed_PRI="2013")AND(Type="AO"),1,0,))
***IFI_COUNT_E_AO_2014=SUM(IF((IFI_Level="E")AND(Signed_PRI="2014")AND(Type="AO"),1,0,))
***IFI_COUNT_D_AO_2014=SUM(IF((IFI_Level="D")AND(Signed_PRI="2014")AND(Type="AO"),1,0,))
***IFI_COUNT_C_AO_2014=SUM(IF((IFI_Level="C")AND(Signed_PRI="2014")AND(Type="AO"),1,0,))
***IFI_COUNT_B_AO_2014=SUM(IF((IFI_Level="B")AND(Signed_PRI="2014")AND(Type="AO"),1,0,))
***IFI_COUNT_A_AO_2014=SUM(IF((IFI_Level="A")AND(Signed_PRI="2014")AND(Type="AO"),1,0,))
***IFI_COUNT_A+_AO_2014=SUM(IF((IFI_Level="A+")AND(Signed_PRI="2014")AND(Type="AO"),1,0,))
***IFI_COUNT_E_AO_2015=SUM(IF((IFI_Level="E")AND(Signed_PRI="2015")AND(Type="AO"),1,0,))
***IFI_COUNT_D_AO_2015=SUM(IF((IFI_Level="D")AND(Signed_PRI="2015")AND(Type="AO"),1,0,))
***IFI_COUNT_C_AO_2015=SUM(IF((IFI_Level="C")AND(Signed_PRI="2015")AND(Type="AO"),1,0,))
***IFI_COUNT_B_AO_2015=SUM(IF((IFI_Level="B")AND(Signed_PRI="2015")AND(Type="AO"),1,0,))
***IFI_COUNT_A_AO_2015=SUM(IF((IFI_Level="A")AND(Signed_PRI="2015")AND(Type="AO"),1,0,))
***IFI_COUNT_A+_AO_2015=SUM(IF((IFI_Level="A+")AND(Signed_PRI="2015")AND(Type="AO"),1,0,))
***IFI_COUNT_E_IM_2006=SUM(IF((IFI_Level="E")AND(Signed_PRI="2006")AND(Type="IM"),1,0,))
***IFI_COUNT_D_IM_2006=SUM(IF((IFI_Level="D")AND(Signed_PRI="2006")AND(Type="IM"),1,0,))
***IFI_COUNT_C_IM_2006=SUM(IF((IFI_Level="C")AND(Signed_PRI="2006")AND(Type="IM"),1,0,))
***IFI_COUNT_B_IM_2006=SUM(IF((IFI_Level="B")AND(Signed_PRI="2006")AND(Type="IM"),1,0,))
***IFI_COUNT_A_IM_2006=SUM(IF((IFI_Level="A")AND(Signed_PRI="2006")AND(Type="IM"),1,0,))
***IFI_COUNT_A+_IM_2006=SUM(IF((IFI_Level="A+")AND(Signed_PRI="2006")AND(Type="IM"),1,0,))
***IFI_COUNT_E_IM_2007=SUM(IF((IFI_Level="E")AND(Signed_PRI="2007")AND(Type="IM"),1,0,))
***IFI_COUNT_D_IM_2007=SUM(IF((IFI_Level="D")AND(Signed_PRI="2007")AND(Type="IM"),1,0,))
***IFI_COUNT_C_IM_2007=SUM(IF((IFI_Level="C")AND(Signed_PRI="2007")AND(Type="IM"),1,0,))
***IFI_COUNT_B_IM_2007=SUM(IF((IFI_Level="B")AND(Signed_PRI="2007")AND(Type="IM"),1,0,))
***IFI_COUNT_A_IM_2007=SUM(IF((IFI_Level="A")AND(Signed_PRI="2007")AND(Type="IM"),1,0,))
***IFI_COUNT_A+_IM_2007=SUM(IF((IFI_Level="A+")AND(Signed_PRI="2007")AND(Type="IM"),1,0,))
***IFI_COUNT_E_IM_2008=SUM(IF((IFI_Level="E")AND(Signed_PRI="2008")AND(Type="IM"),1,0,))
***IFI_COUNT_D_IM_2008=SUM(IF((IFI_Level="D")AND(Signed_PRI="2008")AND(Type="IM"),1,0,))
***IFI_COUNT_C_IM_2008=SUM(IF((IFI_Level="C")AND(Signed_PRI="2008")AND(Type="IM"),1,0,))
***IFI_COUNT_B_IM_2008=SUM(IF((IFI_Level="B")AND(Signed_PRI="2008")AND(Type="IM"),1,0,))
***IFI_COUNT_A_IM_2008=SUM(IF((IFI_Level="A")AND(Signed_PRI="2008")AND(Type="IM"),1,0,))
***IFI_COUNT_A+_IM_2008=SUM(IF((IFI_Level="A+")AND(Signed_PRI="2008")AND(Type="IM"),1,0,))
***IFI_COUNT_E_IM_2009=SUM(IF((IFI_Level="E")AND(Signed_PRI="2009")AND(Type="IM"),1,0,))
***IFI_COUNT_D_IM_2009=SUM(IF((IFI_Level="D")AND(Signed_PRI="2009")AND(Type="IM"),1,0,))
***IFI_COUNT_C_IM_2009=SUM(IF((IFI_Level="C")AND(Signed_PRI="2009")AND(Type="IM"),1,0,))
***IFI_COUNT_B_IM_2009=SUM(IF((IFI_Level="B")AND(Signed_PRI="2009")AND(Type="IM"),1,0,))
***IFI_COUNT_A_IM_2009=SUM(IF((IFI_Level="A")AND(Signed_PRI="2009")AND(Type="IM"),1,0,))
***IFI_COUNT_A+_IM_2009=SUM(IF((IFI_Level="A+")AND(Signed_PRI="2009")AND(Type="IM"),1,0,))
***IFI_COUNT_E_IM_2010=SUM(IF((IFI_Level="E")AND(Signed_PRI="2010")AND(Type="IM"),1,0,))
***IFI_COUNT_D_IM_2010=SUM(IF((IFI_Level="D")AND(Signed_PRI="2010")AND(Type="IM"),1,0,))
***IFI_COUNT_C_IM_2010=SUM(IF((IFI_Level="C")AND(Signed_PRI="2010")AND(Type="IM"),1,0,))
***IFI_COUNT_B_IM_2010=SUM(IF((IFI_Level="B")AND(Signed_PRI="2010")AND(Type="IM"),1,0,))
***IFI_COUNT_A_IM_2010=SUM(IF((IFI_Level="A")AND(Signed_PRI="2010")AND(Type="IM"),1,0,))
***IFI_COUNT_A+_IM_2010=SUM(IF((IFI_Level="A+")AND(Signed_PRI="2010")AND(Type="IM"),1,0,))
***IFI_COUNT_E_IM_2011=SUM(IF((IFI_Level="E")AND(Signed_PRI="2011")AND(Type="IM"),1,0,))
***IFI_COUNT_D_IM_2011=SUM(IF((IFI_Level="D")AND(Signed_PRI="2011")AND(Type="IM"),1,0,))
***IFI_COUNT_C_IM_2011=SUM(IF((IFI_Level="C")AND(Signed_PRI="2011")AND(Type="IM"),1,0,))
***IFI_COUNT_B_IM_2011=SUM(IF((IFI_Level="B")AND(Signed_PRI="2011")AND(Type="IM"),1,0,))
***IFI_COUNT_A_IM_2011=SUM(IF((IFI_Level="A")AND(Signed_PRI="2011")AND(Type="IM"),1,0,))
***IFI_COUNT_A+_IM_2011=SUM(IF((IFI_Level="A+")AND(Signed_PRI="2011")AND(Type="IM"),1,0,))
***IFI_COUNT_E_IM_2012=SUM(IF((IFI_Level="E")AND(Signed_PRI="2012")AND(Type="IM"),1,0,))
***IFI_COUNT_D_IM_2012=SUM(IF((IFI_Level="D")AND(Signed_PRI="2012")AND(Type="IM"),1,0,))
***IFI_COUNT_C_IM_2012=SUM(IF((IFI_Level="C")AND(Signed_PRI="2012")AND(Type="IM"),1,0,))
***IFI_COUNT_B_IM_2012=SUM(IF((IFI_Level="B")AND(Signed_PRI="2012")AND(Type="IM"),1,0,))
***IFI_COUNT_A_IM_2012=SUM(IF((IFI_Level="A")AND(Signed_PRI="2012")AND(Type="IM"),1,0,))
***IFI_COUNT_A+_IM_2012=SUM(IF((IFI_Level="A+")AND(Signed_PRI="2012")AND(Type="IM"),1,0,))
***IFI_COUNT_E_IM_2013=SUM(IF((IFI_Level="E")AND(Signed_PRI="2013")AND(Type="IM"),1,0,))
***IFI_COUNT_D_IM_2013=SUM(IF((IFI_Level="D")AND(Signed_PRI="2013")AND(Type="IM"),1,0,))
***IFI_COUNT_C_IM_2013=SUM(IF((IFI_Level="C")AND(Signed_PRI="2013")AND(Type="IM"),1,0,))
***IFI_COUNT_B_IM_2013=SUM(IF((IFI_Level="B")AND(Signed_PRI="2013")AND(Type="IM"),1,0,))
***IFI_COUNT_A_IM_2013=SUM(IF((IFI_Level="A")AND(Signed_PRI="2013")AND(Type="IM"),1,0,))
***IFI_COUNT_A+_IM_2013=SUM(IF((IFI_Level="A+")AND(Signed_PRI="2013")AND(Type="IM"),1,0,))
***IFI_COUNT_E_IM_2014=SUM(IF((IFI_Level="E")AND(Signed_PRI="2014")AND(Type="IM"),1,0,))
***IFI_COUNT_D_IM_2014=SUM(IF((IFI_Level="D")AND(Signed_PRI="2014")AND(Type="IM"),1,0,))
***IFI_COUNT_C_IM_2014=SUM(IF((IFI_Level="C")AND(Signed_PRI="2014")AND(Type="IM"),1,0,))
***IFI_COUNT_B_IM_2014=SUM(IF((IFI_Level="B")AND(Signed_PRI="2014")AND(Type="IM"),1,0,))
***IFI_COUNT_A_IM_2014=SUM(IF((IFI_Level="A")AND(Signed_PRI="2014")AND(Type="IM"),1,0,))
***IFI_COUNT_A+_IM_2014=SUM(IF((IFI_Level="A+")AND(Signed_PRI="2014")AND(Type="IM"),1,0,))
***IFI_COUNT_E_IM_2015=SUM(IF((IFI_Level="E")AND(Signed_PRI="2015")AND(Type="IM"),1,0,))
***IFI_COUNT_D_IM_2015=SUM(IF((IFI_Level="D")AND(Signed_PRI="2015")AND(Type="IM"),1,0,))
***IFI_COUNT_C_IM_2015=SUM(IF((IFI_Level="C")AND(Signed_PRI="2015")AND(Type="IM"),1,0,))
***IFI_COUNT_B_IM_2015=SUM(IF((IFI_Level="B")AND(Signed_PRI="2015")AND(Type="IM"),1,0,))
***IFI_COUNT_A_IM_2015=SUM(IF((IFI_Level="A")AND(Signed_PRI="2015")AND(Type="IM"),1,0,))
***IFI_COUNT_A+_IM_2015=SUM(IF((IFI_Level="A+")AND(Signed_PRI="2015")AND(Type="IM"),1,0,))
***IFI_COUNT_E_IM_Australia=SUM(IF((IFI_Level="E")AND(Country="Australia")AND(Type="IM"),1,0,))
***IFI_COUNT_D_IM_Australia=SUM(IF((IFI_Level="D")AND(Country="Australia")AND(Type="IM"),1,0,))
***IFI_COUNT_C_IM_Australia=SUM(IF((IFI_Level="C")AND(Country="Australia")AND(Type="IM"),1,0,))
***IFI_COUNT_B_IM_Australia=SUM(IF((IFI_Level="B")AND(Country="Australia")AND(Type="IM"),1,0,))
***IFI_COUNT_A_IM_Australia=SUM(IF((IFI_Level="A")AND(Country="Australia")AND(Type="IM"),1,0,))
***IFI_COUNT_A+_IM_Australia=SUM(IF((IFI_Level="A+")AND(Country="Australia")AND(Type="IM"),1,0,))
***IFI_COUNT_E_IM_Austria=SUM(IF((IFI_Level="E")AND(Country="Austria")AND(Type="IM"),1,0,))
***IFI_COUNT_D_IM_Austria=SUM(IF((IFI_Level="D")AND(Country="Austria")AND(Type="IM"),1,0,))
***IFI_COUNT_C_IM_Austria=SUM(IF((IFI_Level="C")AND(Country="Austria")AND(Type="IM"),1,0,))
***IFI_COUNT_B_IM_Austria=SUM(IF((IFI_Level="B")AND(Country="Austria")AND(Type="IM"),1,0,))
***IFI_COUNT_A_IM_Austria=SUM(IF((IFI_Level="A")AND(Country="Austria")AND(Type="IM"),1,0,))
***IFI_COUNT_A+_IM_Austria=SUM(IF((IFI_Level="A+")AND(Country="Austria")AND(Type="IM"),1,0,))
***IFI_COUNT_E_IM_Belgium=SUM(IF((IFI_Level="E")AND(Country="Belgium")AND(Type="IM"),1,0,))
***IFI_COUNT_D_IM_Belgium=SUM(IF((IFI_Level="D")AND(Country="Belgium")AND(Type="IM"),1,0,))
***IFI_COUNT_C_IM_Belgium=SUM(IF((IFI_Level="C")AND(Country="Belgium")AND(Type="IM"),1,0,))
***IFI_COUNT_B_IM_Belgium=SUM(IF((IFI_Level="B")AND(Country="Belgium")AND(Type="IM"),1,0,))
***IFI_COUNT_A_IM_Belgium=SUM(IF((IFI_Level="A")AND(Country="Belgium")AND(Type="IM"),1,0,))
***IFI_COUNT_A+_IM_Belgium=SUM(IF((IFI_Level="A+")AND(Country="Belgium")AND(Type="IM"),1,0,))
***IFI_COUNT_E_IM_Bermuda=SUM(IF((IFI_Level="E")AND(Country="Bermuda")AND(Type="IM"),1,0,))
***IFI_COUNT_D_IM_Bermuda=SUM(IF((IFI_Level="D")AND(Country="Bermuda")AND(Type="IM"),1,0,))
***IFI_COUNT_C_IM_Bermuda=SUM(IF((IFI_Level="C")AND(Country="Bermuda")AND(Type="IM"),1,0,))
***IFI_COUNT_B_IM_Bermuda=SUM(IF((IFI_Level="B")AND(Country="Bermuda")AND(Type="IM"),1,0,))
***IFI_COUNT_A_IM_Bermuda=SUM(IF((IFI_Level="A")AND(Country="Bermuda")AND(Type="IM"),1,0,))
***IFI_COUNT_A+_IM_Bermuda=SUM(IF((IFI_Level="A+")AND(Country="Bermuda")AND(Type="IM"),1,0,))
***IFI_COUNT_E_IM_Botswana=SUM(IF((IFI_Level="E")AND(Country="Botswana")AND(Type="IM"),1,0,))
***IFI_COUNT_D_IM_Botswana=SUM(IF((IFI_Level="D")AND(Country="Botswana")AND(Type="IM"),1,0,))
***IFI_COUNT_C_IM_Botswana=SUM(IF((IFI_Level="C")AND(Country="Botswana")AND(Type="IM"),1,0,))
***IFI_COUNT_B_IM_Botswana=SUM(IF((IFI_Level="B")AND(Country="Botswana")AND(Type="IM"),1,0,))
***IFI_COUNT_A_IM_Botswana=SUM(IF((IFI_Level="A")AND(Country="Botswana")AND(Type="IM"),1,0,))
***IFI_COUNT_A+_IM_Botswana=SUM(IF((IFI_Level="A+")AND(Country="Botswana")AND(Type="IM"),1,0,))
***IFI_COUNT_E_IM_Brazil=SUM(IF((IFI_Level="E")AND(Country="Brazil")AND(Type="IM"),1,0,))
***IFI_COUNT_D_IM_Brazil=SUM(IF((IFI_Level="D")AND(Country="Brazil")AND(Type="IM"),1,0,))
***IFI_COUNT_C_IM_Brazil=SUM(IF((IFI_Level="C")AND(Country="Brazil")AND(Type="IM"),1,0,))
***IFI_COUNT_B_IM_Brazil=SUM(IF((IFI_Level="B")AND(Country="Brazil")AND(Type="IM"),1,0,))
***IFI_COUNT_A_IM_Brazil=SUM(IF((IFI_Level="A")AND(Country="Brazil")AND(Type="IM"),1,0,))
***IFI_COUNT_A+_IM_Brazil=SUM(IF((IFI_Level="A+")AND(Country="Brazil")AND(Type="IM"),1,0,))
***IFI_COUNT_E_IM_Canada=SUM(IF((IFI_Level="E")AND(Country="Canada")AND(Type="IM"),1,0,))
***IFI_COUNT_D_IM_Canada=SUM(IF((IFI_Level="D")AND(Country="Canada")AND(Type="IM"),1,0,))
***IFI_COUNT_C_IM_Canada=SUM(IF((IFI_Level="C")AND(Country="Canada")AND(Type="IM"),1,0,))
***IFI_COUNT_B_IM_Canada=SUM(IF((IFI_Level="B")AND(Country="Canada")AND(Type="IM"),1,0,))
***IFI_COUNT_A_IM_Canada=SUM(IF((IFI_Level="A")AND(Country="Canada")AND(Type="IM"),1,0,))
***IFI_COUNT_A+_IM_Canada=SUM(IF((IFI_Level="A+")AND(Country="Canada")AND(Type="IM"),1,0,))
***IFI_COUNT_E_IM_China=SUM(IF((IFI_Level="E")AND(Country="China")AND(Type="IM"),1,0,))
***IFI_COUNT_D_IM_China=SUM(IF((IFI_Level="D")AND(Country="China")AND(Type="IM"),1,0,))
***IFI_COUNT_C_IM_China=SUM(IF((IFI_Level="C")AND(Country="China")AND(Type="IM"),1,0,))
***IFI_COUNT_B_IM_China=SUM(IF((IFI_Level="B")AND(Country="China")AND(Type="IM"),1,0,))
***IFI_COUNT_A_IM_China=SUM(IF((IFI_Level="A")AND(Country="China")AND(Type="IM"),1,0,))
***IFI_COUNT_A+_IM_China=SUM(IF((IFI_Level="A+")AND(Country="China")AND(Type="IM"),1,0,))
***IFI_COUNT_E_IM_Colombia=SUM(IF((IFI_Level="E")AND(Country="Colombia")AND(Type="IM"),1,0,))
***IFI_COUNT_D_IM_Colombia=SUM(IF((IFI_Level="D")AND(Country="Colombia")AND(Type="IM"),1,0,))
***IFI_COUNT_C_IM_Colombia=SUM(IF((IFI_Level="C")AND(Country="Colombia")AND(Type="IM"),1,0,))
***IFI_COUNT_B_IM_Colombia=SUM(IF((IFI_Level="B")AND(Country="Colombia")AND(Type="IM"),1,0,))
***IFI_COUNT_A_IM_Colombia=SUM(IF((IFI_Level="A")AND(Country="Colombia")AND(Type="IM"),1,0,))
***IFI_COUNT_A+_IM_Colombia=SUM(IF((IFI_Level="A+")AND(Country="Colombia")AND(Type="IM"),1,0,))
***IFI_COUNT_E_IM_Denmark=SUM(IF((IFI_Level="E")AND(Country="Denmark")AND(Type="IM"),1,0,))
***IFI_COUNT_D_IM_Denmark=SUM(IF((IFI_Level="D")AND(Country="Denmark")AND(Type="IM"),1,0,))
***IFI_COUNT_C_IM_Denmark=SUM(IF((IFI_Level="C")AND(Country="Denmark")AND(Type="IM"),1,0,))
***IFI_COUNT_B_IM_Denmark=SUM(IF((IFI_Level="B")AND(Country="Denmark")AND(Type="IM"),1,0,))
***IFI_COUNT_A_IM_Denmark=SUM(IF((IFI_Level="A")AND(Country="Denmark")AND(Type="IM"),1,0,))
***IFI_COUNT_A+_IM_Denmark=SUM(IF((IFI_Level="A+")AND(Country="Denmark")AND(Type="IM"),1,0,))
***IFI_COUNT_E_IM_Estonia=SUM(IF((IFI_Level="E")AND(Country="Estonia")AND(Type="IM"),1,0,))
***IFI_COUNT_D_IM_Estonia=SUM(IF((IFI_Level="D")AND(Country="Estonia")AND(Type="IM"),1,0,))
***IFI_COUNT_C_IM_Estonia=SUM(IF((IFI_Level="C")AND(Country="Estonia")AND(Type="IM"),1,0,))
***IFI_COUNT_B_IM_Estonia=SUM(IF((IFI_Level="B")AND(Country="Estonia")AND(Type="IM"),1,0,))
***IFI_COUNT_A_IM_Estonia=SUM(IF((IFI_Level="A")AND(Country="Estonia")AND(Type="IM"),1,0,))
***IFI_COUNT_A+_IM_Estonia=SUM(IF((IFI_Level="A+")AND(Country="Estonia")AND(Type="IM"),1,0,))
***IFI_COUNT_E_IM_Finland=SUM(IF((IFI_Level="E")AND(Country="Finland")AND(Type="IM"),1,0,))
***IFI_COUNT_D_IM_Finland=SUM(IF((IFI_Level="D")AND(Country="Finland")AND(Type="IM"),1,0,))
***IFI_COUNT_C_IM_Finland=SUM(IF((IFI_Level="C")AND(Country="Finland")AND(Type="IM"),1,0,))
***IFI_COUNT_B_IM_Finland=SUM(IF((IFI_Level="B")AND(Country="Finland")AND(Type="IM"),1,0,))
***IFI_COUNT_A_IM_Finland=SUM(IF((IFI_Level="A")AND(Country="Finland")AND(Type="IM"),1,0,))
***IFI_COUNT_A+_IM_Finland=SUM(IF((IFI_Level="A+")AND(Country="Finland")AND(Type="IM"),1,0,))
***IFI_COUNT_E_IM_France=SUM(IF((IFI_Level="E")AND(Country="France")AND(Type="IM"),1,0,))
***IFI_COUNT_D_IM_France=SUM(IF((IFI_Level="D")AND(Country="France")AND(Type="IM"),1,0,))
***IFI_COUNT_C_IM_France=SUM(IF((IFI_Level="C")AND(Country="France")AND(Type="IM"),1,0,))
***IFI_COUNT_B_IM_France=SUM(IF((IFI_Level="B")AND(Country="France")AND(Type="IM"),1,0,))
***IFI_COUNT_A_IM_France=SUM(IF((IFI_Level="A")AND(Country="France")AND(Type="IM"),1,0,))
***IFI_COUNT_A+_IM_France=SUM(IF((IFI_Level="A+")AND(Country="France")AND(Type="IM"),1,0,))
***IFI_COUNT_E_IM_Germany=SUM(IF((IFI_Level="E")AND(Country="Germany")AND(Type="IM"),1,0,))
***IFI_COUNT_D_IM_Germany=SUM(IF((IFI_Level="D")AND(Country="Germany")AND(Type="IM"),1,0,))
***IFI_COUNT_C_IM_Germany=SUM(IF((IFI_Level="C")AND(Country="Germany")AND(Type="IM"),1,0,))
***IFI_COUNT_B_IM_Germany=SUM(IF((IFI_Level="B")AND(Country="Germany")AND(Type="IM"),1,0,))
***IFI_COUNT_A_IM_Germany=SUM(IF((IFI_Level="A")AND(Country="Germany")AND(Type="IM"),1,0,))
***IFI_COUNT_A+_IM_Germany=SUM(IF((IFI_Level="A+")AND(Country="Germany")AND(Type="IM"),1,0,))
***IFI_COUNT_E_IM_Hong Kong=SUM(IF((IFI_Level="E")AND(Country="Hong Kong")AND(Type="IM"),1,0,))
***IFI_COUNT_D_IM_Hong Kong=SUM(IF((IFI_Level="D")AND(Country="Hong Kong")AND(Type="IM"),1,0,))
***IFI_COUNT_C_IM_Hong Kong=SUM(IF((IFI_Level="C")AND(Country="Hong Kong")AND(Type="IM"),1,0,))
***IFI_COUNT_B_IM_Hong Kong=SUM(IF((IFI_Level="B")AND(Country="Hong Kong")AND(Type="IM"),1,0,))
***IFI_COUNT_A_IM_Hong Kong=SUM(IF((IFI_Level="A")AND(Country="Hong Kong")AND(Type="IM"),1,0,))
***IFI_COUNT_A+_IM_Hong Kong=SUM(IF((IFI_Level="A+")AND(Country="Hong Kong")AND(Type="IM"),1,0,))
***IFI_COUNT_E_IM_Iceland=SUM(IF((IFI_Level="E")AND(Country="Iceland")AND(Type="IM"),1,0,))
***IFI_COUNT_D_IM_Iceland=SUM(IF((IFI_Level="D")AND(Country="Iceland")AND(Type="IM"),1,0,))
***IFI_COUNT_C_IM_Iceland=SUM(IF((IFI_Level="C")AND(Country="Iceland")AND(Type="IM"),1,0,))
***IFI_COUNT_B_IM_Iceland=SUM(IF((IFI_Level="B")AND(Country="Iceland")AND(Type="IM"),1,0,))
***IFI_COUNT_A_IM_Iceland=SUM(IF((IFI_Level="A")AND(Country="Iceland")AND(Type="IM"),1,0,))
***IFI_COUNT_A+_IM_Iceland=SUM(IF((IFI_Level="A+")AND(Country="Iceland")AND(Type="IM"),1,0,))
***IFI_COUNT_E_IM_India=SUM(IF((IFI_Level="E")AND(Country="India")AND(Type="IM"),1,0,))
***IFI_COUNT_D_IM_India=SUM(IF((IFI_Level="D")AND(Country="India")AND(Type="IM"),1,0,))
***IFI_COUNT_C_IM_India=SUM(IF((IFI_Level="C")AND(Country="India")AND(Type="IM"),1,0,))
***IFI_COUNT_B_IM_India=SUM(IF((IFI_Level="B")AND(Country="India")AND(Type="IM"),1,0,))
***IFI_COUNT_A_IM_India=SUM(IF((IFI_Level="A")AND(Country="India")AND(Type="IM"),1,0,))
***IFI_COUNT_A+_IM_India=SUM(IF((IFI_Level="A+")AND(Country="India")AND(Type="IM"),1,0,))
***IFI_COUNT_E_IM_Indonesia=SUM(IF((IFI_Level="E")AND(Country="Indonesia")AND(Type="IM"),1,0,))
***IFI_COUNT_D_IM_Indonesia=SUM(IF((IFI_Level="D")AND(Country="Indonesia")AND(Type="IM"),1,0,))
***IFI_COUNT_C_IM_Indonesia=SUM(IF((IFI_Level="C")AND(Country="Indonesia")AND(Type="IM"),1,0,))
***IFI_COUNT_B_IM_Indonesia=SUM(IF((IFI_Level="B")AND(Country="Indonesia")AND(Type="IM"),1,0,))
***IFI_COUNT_A_IM_Indonesia=SUM(IF((IFI_Level="A")AND(Country="Indonesia")AND(Type="IM"),1,0,))
***IFI_COUNT_A+_IM_Indonesia=SUM(IF((IFI_Level="A+")AND(Country="Indonesia")AND(Type="IM"),1,0,))
***IFI_COUNT_E_IM_Ireland=SUM(IF((IFI_Level="E")AND(Country="Ireland")AND(Type="IM"),1,0,))
***IFI_COUNT_D_IM_Ireland=SUM(IF((IFI_Level="D")AND(Country="Ireland")AND(Type="IM"),1,0,))
***IFI_COUNT_C_IM_Ireland=SUM(IF((IFI_Level="C")AND(Country="Ireland")AND(Type="IM"),1,0,))
***IFI_COUNT_B_IM_Ireland=SUM(IF((IFI_Level="B")AND(Country="Ireland")AND(Type="IM"),1,0,))
***IFI_COUNT_A_IM_Ireland=SUM(IF((IFI_Level="A")AND(Country="Ireland")AND(Type="IM"),1,0,))
***IFI_COUNT_A+_IM_Ireland=SUM(IF((IFI_Level="A+")AND(Country="Ireland")AND(Type="IM"),1,0,))
***IFI_COUNT_E_IM_Italy=SUM(IF((IFI_Level="E")AND(Country="Italy")AND(Type="IM"),1,0,))
***IFI_COUNT_D_IM_Italy=SUM(IF((IFI_Level="D")AND(Country="Italy")AND(Type="IM"),1,0,))
***IFI_COUNT_C_IM_Italy=SUM(IF((IFI_Level="C")AND(Country="Italy")AND(Type="IM"),1,0,))
***IFI_COUNT_B_IM_Italy=SUM(IF((IFI_Level="B")AND(Country="Italy")AND(Type="IM"),1,0,))
***IFI_COUNT_A_IM_Italy=SUM(IF((IFI_Level="A")AND(Country="Italy")AND(Type="IM"),1,0,))
***IFI_COUNT_A+_IM_Italy=SUM(IF((IFI_Level="A+")AND(Country="Italy")AND(Type="IM"),1,0,))
***IFI_COUNT_E_IM_Japan=SUM(IF((IFI_Level="E")AND(Country="Japan")AND(Type="IM"),1,0,))
***IFI_COUNT_D_IM_Japan=SUM(IF((IFI_Level="D")AND(Country="Japan")AND(Type="IM"),1,0,))
***IFI_COUNT_C_IM_Japan=SUM(IF((IFI_Level="C")AND(Country="Japan")AND(Type="IM"),1,0,))
***IFI_COUNT_B_IM_Japan=SUM(IF((IFI_Level="B")AND(Country="Japan")AND(Type="IM"),1,0,))
***IFI_COUNT_A_IM_Japan=SUM(IF((IFI_Level="A")AND(Country="Japan")AND(Type="IM"),1,0,))
***IFI_COUNT_A+_IM_Japan=SUM(IF((IFI_Level="A+")AND(Country="Japan")AND(Type="IM"),1,0,))
***IFI_COUNT_E_IM_Liechtenstein=SUM(IF((IFI_Level="E")AND(Country="Liechtenstein")AND(Type="IM"),1,0,))
***IFI_COUNT_D_IM_Liechtenstein=SUM(IF((IFI_Level="D")AND(Country="Liechtenstein")AND(Type="IM"),1,0,))
***IFI_COUNT_C_IM_Liechtenstein=SUM(IF((IFI_Level="C")AND(Country="Liechtenstein")AND(Type="IM"),1,0,))
***IFI_COUNT_B_IM_Liechtenstein=SUM(IF((IFI_Level="B")AND(Country="Liechtenstein")AND(Type="IM"),1,0,))
***IFI_COUNT_A_IM_Liechtenstein=SUM(IF((IFI_Level="A")AND(Country="Liechtenstein")AND(Type="IM"),1,0,))
***IFI_COUNT_A+_IM_Liechtenstein=SUM(IF((IFI_Level="A+")AND(Country="Liechtenstein")AND(Type="IM"),1,0,))
***IFI_COUNT_E_IM_Luxembourg=SUM(IF((IFI_Level="E")AND(Country="Luxembourg")AND(Type="IM"),1,0,))
***IFI_COUNT_D_IM_Luxembourg=SUM(IF((IFI_Level="D")AND(Country="Luxembourg")AND(Type="IM"),1,0,))
***IFI_COUNT_C_IM_Luxembourg=SUM(IF((IFI_Level="C")AND(Country="Luxembourg")AND(Type="IM"),1,0,))
***IFI_COUNT_B_IM_Luxembourg=SUM(IF((IFI_Level="B")AND(Country="Luxembourg")AND(Type="IM"),1,0,))
***IFI_COUNT_A_IM_Luxembourg=SUM(IF((IFI_Level="A")AND(Country="Luxembourg")AND(Type="IM"),1,0,))
***IFI_COUNT_A+_IM_Luxembourg=SUM(IF((IFI_Level="A+")AND(Country="Luxembourg")AND(Type="IM"),1,0,))
***IFI_COUNT_E_IM_Malaysia=SUM(IF((IFI_Level="E")AND(Country="Malaysia")AND(Type="IM"),1,0,))
***IFI_COUNT_D_IM_Malaysia=SUM(IF((IFI_Level="D")AND(Country="Malaysia")AND(Type="IM"),1,0,))
***IFI_COUNT_C_IM_Malaysia=SUM(IF((IFI_Level="C")AND(Country="Malaysia")AND(Type="IM"),1,0,))
***IFI_COUNT_B_IM_Malaysia=SUM(IF((IFI_Level="B")AND(Country="Malaysia")AND(Type="IM"),1,0,))
***IFI_COUNT_A_IM_Malaysia=SUM(IF((IFI_Level="A")AND(Country="Malaysia")AND(Type="IM"),1,0,))
***IFI_COUNT_A+_IM_Malaysia=SUM(IF((IFI_Level="A+")AND(Country="Malaysia")AND(Type="IM"),1,0,))
***IFI_COUNT_E_IM_Mauritius=SUM(IF((IFI_Level="E")AND(Country="Mauritius")AND(Type="IM"),1,0,))
***IFI_COUNT_D_IM_Mauritius=SUM(IF((IFI_Level="D")AND(Country="Mauritius")AND(Type="IM"),1,0,))
***IFI_COUNT_C_IM_Mauritius=SUM(IF((IFI_Level="C")AND(Country="Mauritius")AND(Type="IM"),1,0,))
***IFI_COUNT_B_IM_Mauritius=SUM(IF((IFI_Level="B")AND(Country="Mauritius")AND(Type="IM"),1,0,))
***IFI_COUNT_A_IM_Mauritius=SUM(IF((IFI_Level="A")AND(Country="Mauritius")AND(Type="IM"),1,0,))
***IFI_COUNT_A+_IM_Mauritius=SUM(IF((IFI_Level="A+")AND(Country="Mauritius")AND(Type="IM"),1,0,))
***IFI_COUNT_E_IM_Namibia=SUM(IF((IFI_Level="E")AND(Country="Namibia")AND(Type="IM"),1,0,))
***IFI_COUNT_D_IM_Namibia=SUM(IF((IFI_Level="D")AND(Country="Namibia")AND(Type="IM"),1,0,))
***IFI_COUNT_C_IM_Namibia=SUM(IF((IFI_Level="C")AND(Country="Namibia")AND(Type="IM"),1,0,))
***IFI_COUNT_B_IM_Namibia=SUM(IF((IFI_Level="B")AND(Country="Namibia")AND(Type="IM"),1,0,))
***IFI_COUNT_A_IM_Namibia=SUM(IF((IFI_Level="A")AND(Country="Namibia")AND(Type="IM"),1,0,))
***IFI_COUNT_A+_IM_Namibia=SUM(IF((IFI_Level="A+")AND(Country="Namibia")AND(Type="IM"),1,0,))
***IFI_COUNT_E_IM_Netherlands=SUM(IF((IFI_Level="E")AND(Country="Netherlands")AND(Type="IM"),1,0,))
***IFI_COUNT_D_IM_Netherlands=SUM(IF((IFI_Level="D")AND(Country="Netherlands")AND(Type="IM"),1,0,))
***IFI_COUNT_C_IM_Netherlands=SUM(IF((IFI_Level="C")AND(Country="Netherlands")AND(Type="IM"),1,0,))
***IFI_COUNT_B_IM_Netherlands=SUM(IF((IFI_Level="B")AND(Country="Netherlands")AND(Type="IM"),1,0,))
***IFI_COUNT_A_IM_Netherlands=SUM(IF((IFI_Level="A")AND(Country="Netherlands")AND(Type="IM"),1,0,))
***IFI_COUNT_A+_IM_Netherlands=SUM(IF((IFI_Level="A+")AND(Country="Netherlands")AND(Type="IM"),1,0,))
***IFI_COUNT_E_IM_New Zealand=SUM(IF((IFI_Level="E")AND(Country="New Zealand")AND(Type="IM"),1,0,))
***IFI_COUNT_D_IM_New Zealand=SUM(IF((IFI_Level="D")AND(Country="New Zealand")AND(Type="IM"),1,0,))
***IFI_COUNT_C_IM_New Zealand=SUM(IF((IFI_Level="C")AND(Country="New Zealand")AND(Type="IM"),1,0,))
***IFI_COUNT_B_IM_New Zealand=SUM(IF((IFI_Level="B")AND(Country="New Zealand")AND(Type="IM"),1,0,))
***IFI_COUNT_A_IM_New Zealand=SUM(IF((IFI_Level="A")AND(Country="New Zealand")AND(Type="IM"),1,0,))
***IFI_COUNT_A+_IM_New Zealand=SUM(IF((IFI_Level="A+")AND(Country="New Zealand")AND(Type="IM"),1,0,))
***IFI_COUNT_E_IM_Norway=SUM(IF((IFI_Level="E")AND(Country="Norway")AND(Type="IM"),1,0,))
***IFI_COUNT_D_IM_Norway=SUM(IF((IFI_Level="D")AND(Country="Norway")AND(Type="IM"),1,0,))
***IFI_COUNT_C_IM_Norway=SUM(IF((IFI_Level="C")AND(Country="Norway")AND(Type="IM"),1,0,))
***IFI_COUNT_B_IM_Norway=SUM(IF((IFI_Level="B")AND(Country="Norway")AND(Type="IM"),1,0,))
***IFI_COUNT_A_IM_Norway=SUM(IF((IFI_Level="A")AND(Country="Norway")AND(Type="IM"),1,0,))
***IFI_COUNT_A+_IM_Norway=SUM(IF((IFI_Level="A+")AND(Country="Norway")AND(Type="IM"),1,0,))
***IFI_COUNT_E_IM_Nigeria=SUM(IF((IFI_Level="E")AND(Country="Nigeria")AND(Type="IM"),1,0,))
***IFI_COUNT_D_IM_Nigeria=SUM(IF((IFI_Level="D")AND(Country="Nigeria")AND(Type="IM"),1,0,))
***IFI_COUNT_C_IM_Nigeria=SUM(IF((IFI_Level="C")AND(Country="Nigeria")AND(Type="IM"),1,0,))
***IFI_COUNT_B_IM_Nigeria=SUM(IF((IFI_Level="B")AND(Country="Nigeria")AND(Type="IM"),1,0,))
***IFI_COUNT_A_IM_Nigeria=SUM(IF((IFI_Level="A")AND(Country="Nigeria")AND(Type="IM"),1,0,))
***IFI_COUNT_A+_IM_Nigeria=SUM(IF((IFI_Level="A+")AND(Country="Nigeria")AND(Type="IM"),1,0,))
***IFI_COUNT_E_IM_Peru=SUM(IF((IFI_Level="E")AND(Country="Peru")AND(Type="IM"),1,0,))
***IFI_COUNT_D_IM_Peru=SUM(IF((IFI_Level="D")AND(Country="Peru")AND(Type="IM"),1,0,))
***IFI_COUNT_C_IM_Peru=SUM(IF((IFI_Level="C")AND(Country="Peru")AND(Type="IM"),1,0,))
***IFI_COUNT_B_IM_Peru=SUM(IF((IFI_Level="B")AND(Country="Peru")AND(Type="IM"),1,0,))
***IFI_COUNT_A_IM_Peru=SUM(IF((IFI_Level="A")AND(Country="Peru")AND(Type="IM"),1,0,))
***IFI_COUNT_A+_IM_Peru=SUM(IF((IFI_Level="A+")AND(Country="Peru")AND(Type="IM"),1,0,))
***IFI_COUNT_E_IM_Puerto Rico=SUM(IF((IFI_Level="E")AND(Country="Puerto Rico")AND(Type="IM"),1,0,))
***IFI_COUNT_D_IM_Puerto Rico=SUM(IF((IFI_Level="D")AND(Country="Puerto Rico")AND(Type="IM"),1,0,))
***IFI_COUNT_C_IM_Puerto Rico=SUM(IF((IFI_Level="C")AND(Country="Puerto Rico")AND(Type="IM"),1,0,))
***IFI_COUNT_B_IM_Puerto Rico=SUM(IF((IFI_Level="B")AND(Country="Puerto Rico")AND(Type="IM"),1,0,))
***IFI_COUNT_A_IM_Puerto Rico=SUM(IF((IFI_Level="A")AND(Country="Puerto Rico")AND(Type="IM"),1,0,))
***IFI_COUNT_A+_IM_Puerto Rico=SUM(IF((IFI_Level="A+")AND(Country="Puerto Rico")AND(Type="IM"),1,0,))
***IFI_COUNT_E_IM_Russia=SUM(IF((IFI_Level="E")AND(Country="Russia")AND(Type="IM"),1,0,))
***IFI_COUNT_D_IM_Russia=SUM(IF((IFI_Level="D")AND(Country="Russia")AND(Type="IM"),1,0,))
***IFI_COUNT_C_IM_Russia=SUM(IF((IFI_Level="C")AND(Country="Russia")AND(Type="IM"),1,0,))
***IFI_COUNT_B_IM_Russia=SUM(IF((IFI_Level="B")AND(Country="Russia")AND(Type="IM"),1,0,))
***IFI_COUNT_A_IM_Russia=SUM(IF((IFI_Level="A")AND(Country="Russia")AND(Type="IM"),1,0,))
***IFI_COUNT_A+_IM_Russia=SUM(IF((IFI_Level="A+")AND(Country="Russia")AND(Type="IM"),1,0,))
***IFI_COUNT_E_IM_Saudi Arabia=SUM(IF((IFI_Level="E")AND(Country="Saudi Arabia")AND(Type="IM"),1,0,))
***IFI_COUNT_D_IM_Saudi Arabia=SUM(IF((IFI_Level="D")AND(Country="Saudi Arabia")AND(Type="IM"),1,0,))
***IFI_COUNT_C_IM_Saudi Arabia=SUM(IF((IFI_Level="C")AND(Country="Saudi Arabia")AND(Type="IM"),1,0,))
***IFI_COUNT_B_IM_Saudi Arabia=SUM(IF((IFI_Level="B")AND(Country="Saudi Arabia")AND(Type="IM"),1,0,))
***IFI_COUNT_A_IM_Saudi Arabia=SUM(IF((IFI_Level="A")AND(Country="Saudi Arabia")AND(Type="IM"),1,0,))
***IFI_COUNT_A+_IM_Saudi Arabia=SUM(IF((IFI_Level="A+")AND(Country="Saudi Arabia")AND(Type="IM"),1,0,))
***IFI_COUNT_E_IM_Singapore=SUM(IF((IFI_Level="E")AND(Country="Singapore")AND(Type="IM"),1,0,))
***IFI_COUNT_D_IM_Singapore=SUM(IF((IFI_Level="D")AND(Country="Singapore")AND(Type="IM"),1,0,))
***IFI_COUNT_C_IM_Singapore=SUM(IF((IFI_Level="C")AND(Country="Singapore")AND(Type="IM"),1,0,))
***IFI_COUNT_B_IM_Singapore=SUM(IF((IFI_Level="B")AND(Country="Singapore")AND(Type="IM"),1,0,))
***IFI_COUNT_A_IM_Singapore=SUM(IF((IFI_Level="A")AND(Country="Singapore")AND(Type="IM"),1,0,))
***IFI_COUNT_A+_IM_Singapore=SUM(IF((IFI_Level="A+")AND(Country="Singapore")AND(Type="IM"),1,0,))
***IFI_COUNT_E_IM_South Africa=SUM(IF((IFI_Level="E")AND(Country="South Africa")AND(Type="IM"),1,0,))
***IFI_COUNT_D_IM_South Africa=SUM(IF((IFI_Level="D")AND(Country="South Africa")AND(Type="IM"),1,0,))
***IFI_COUNT_C_IM_South Africa=SUM(IF((IFI_Level="C")AND(Country="South Africa")AND(Type="IM"),1,0,))
***IFI_COUNT_B_IM_South Africa=SUM(IF((IFI_Level="B")AND(Country="South Africa")AND(Type="IM"),1,0,))
***IFI_COUNT_A_IM_South Africa=SUM(IF((IFI_Level="A")AND(Country="South Africa")AND(Type="IM"),1,0,))
***IFI_COUNT_A+_IM_South Africa=SUM(IF((IFI_Level="A+")AND(Country="South Africa")AND(Type="IM"),1,0,))
***IFI_COUNT_E_IM_Spain=SUM(IF((IFI_Level="E")AND(Country="Spain")AND(Type="IM"),1,0,))
***IFI_COUNT_D_IM_Spain=SUM(IF((IFI_Level="D")AND(Country="Spain")AND(Type="IM"),1,0,))
***IFI_COUNT_C_IM_Spain=SUM(IF((IFI_Level="C")AND(Country="Spain")AND(Type="IM"),1,0,))
***IFI_COUNT_B_IM_Spain=SUM(IF((IFI_Level="B")AND(Country="Spain")AND(Type="IM"),1,0,))
***IFI_COUNT_A_IM_Spain=SUM(IF((IFI_Level="A")AND(Country="Spain")AND(Type="IM"),1,0,))
***IFI_COUNT_A+_IM_Spain=SUM(IF((IFI_Level="A+")AND(Country="Spain")AND(Type="IM"),1,0,))
***IFI_COUNT_E_IM_Sweden=SUM(IF((IFI_Level="E")AND(Country="Sweden")AND(Type="IM"),1,0,))
***IFI_COUNT_D_IM_Sweden=SUM(IF((IFI_Level="D")AND(Country="Sweden")AND(Type="IM"),1,0,))
***IFI_COUNT_C_IM_Sweden=SUM(IF((IFI_Level="C")AND(Country="Sweden")AND(Type="IM"),1,0,))
***IFI_COUNT_B_IM_Sweden=SUM(IF((IFI_Level="B")AND(Country="Sweden")AND(Type="IM"),1,0,))
***IFI_COUNT_A_IM_Sweden=SUM(IF((IFI_Level="A")AND(Country="Sweden")AND(Type="IM"),1,0,))
***IFI_COUNT_A+_IM_Sweden=SUM(IF((IFI_Level="A+")AND(Country="Sweden")AND(Type="IM"),1,0,))
***IFI_COUNT_E_IM_Switzerland=SUM(IF((IFI_Level="E")AND(Country="Switzerland")AND(Type="IM"),1,0,))
***IFI_COUNT_D_IM_Switzerland=SUM(IF((IFI_Level="D")AND(Country="Switzerland")AND(Type="IM"),1,0,))
***IFI_COUNT_C_IM_Switzerland=SUM(IF((IFI_Level="C")AND(Country="Switzerland")AND(Type="IM"),1,0,))
***IFI_COUNT_B_IM_Switzerland=SUM(IF((IFI_Level="B")AND(Country="Switzerland")AND(Type="IM"),1,0,))
***IFI_COUNT_A_IM_Switzerland=SUM(IF((IFI_Level="A")AND(Country="Switzerland")AND(Type="IM"),1,0,))
***IFI_COUNT_A+_IM_Switzerland=SUM(IF((IFI_Level="A+")AND(Country="Switzerland")AND(Type="IM"),1,0,))
***IFI_COUNT_E_IM_Thailand=SUM(IF((IFI_Level="E")AND(Country="Thailand")AND(Type="IM"),1,0,))
***IFI_COUNT_D_IM_Thailand=SUM(IF((IFI_Level="D")AND(Country="Thailand")AND(Type="IM"),1,0,))
***IFI_COUNT_C_IM_Thailand=SUM(IF((IFI_Level="C")AND(Country="Thailand")AND(Type="IM"),1,0,))
***IFI_COUNT_B_IM_Thailand=SUM(IF((IFI_Level="B")AND(Country="Thailand")AND(Type="IM"),1,0,))
***IFI_COUNT_A_IM_Thailand=SUM(IF((IFI_Level="A")AND(Country="Thailand")AND(Type="IM"),1,0,))
***IFI_COUNT_A+_IM_Thailand=SUM(IF((IFI_Level="A+")AND(Country="Thailand")AND(Type="IM"),1,0,))
***IFI_COUNT_E_IM_Turkey=SUM(IF((IFI_Level="E")AND(Country="Turkey")AND(Type="IM"),1,0,))
***IFI_COUNT_D_IM_Turkey=SUM(IF((IFI_Level="D")AND(Country="Turkey")AND(Type="IM"),1,0,))
***IFI_COUNT_C_IM_Turkey=SUM(IF((IFI_Level="C")AND(Country="Turkey")AND(Type="IM"),1,0,))
***IFI_COUNT_B_IM_Turkey=SUM(IF((IFI_Level="B")AND(Country="Turkey")AND(Type="IM"),1,0,))
***IFI_COUNT_A_IM_Turkey=SUM(IF((IFI_Level="A")AND(Country="Turkey")AND(Type="IM"),1,0,))
***IFI_COUNT_A+_IM_Turkey=SUM(IF((IFI_Level="A+")AND(Country="Turkey")AND(Type="IM"),1,0,))
***IFI_COUNT_E_IM_UAE=SUM(IF((IFI_Level="E")AND(Country="UAE")AND(Type="IM"),1,0,))
***IFI_COUNT_D_IM_UAE=SUM(IF((IFI_Level="D")AND(Country="UAE")AND(Type="IM"),1,0,))
***IFI_COUNT_C_IM_UAE=SUM(IF((IFI_Level="C")AND(Country="UAE")AND(Type="IM"),1,0,))
***IFI_COUNT_B_IM_UAE=SUM(IF((IFI_Level="B")AND(Country="UAE")AND(Type="IM"),1,0,))
***IFI_COUNT_A_IM_UAE=SUM(IF((IFI_Level="A")AND(Country="UAE")AND(Type="IM"),1,0,))
***IFI_COUNT_A+_IM_UAE=SUM(IF((IFI_Level="A+")AND(Country="UAE")AND(Type="IM"),1,0,))
***IFI_COUNT_E_IM_UK=SUM(IF((IFI_Level="E")AND(Country="UK")AND(Type="IM"),1,0,))
***IFI_COUNT_D_IM_UK=SUM(IF((IFI_Level="D")AND(Country="UK")AND(Type="IM"),1,0,))
***IFI_COUNT_C_IM_UK=SUM(IF((IFI_Level="C")AND(Country="UK")AND(Type="IM"),1,0,))
***IFI_COUNT_B_IM_UK=SUM(IF((IFI_Level="B")AND(Country="UK")AND(Type="IM"),1,0,))
***IFI_COUNT_A_IM_UK=SUM(IF((IFI_Level="A")AND(Country="UK")AND(Type="IM"),1,0,))
***IFI_COUNT_A+_IM_UK=SUM(IF((IFI_Level="A+")AND(Country="UK")AND(Type="IM"),1,0,))
***IFI_COUNT_E_IM_USA=SUM(IF((IFI_Level="E")AND(Country="USA")AND(Type="IM"),1,0,))
***IFI_COUNT_D_IM_USA=SUM(IF((IFI_Level="D")AND(Country="USA")AND(Type="IM"),1,0,))
***IFI_COUNT_C_IM_USA=SUM(IF((IFI_Level="C")AND(Country="USA")AND(Type="IM"),1,0,))
***IFI_COUNT_B_IM_USA=SUM(IF((IFI_Level="B")AND(Country="USA")AND(Type="IM"),1,0,))
***IFI_COUNT_A_IM_USA=SUM(IF((IFI_Level="A")AND(Country="USA")AND(Type="IM"),1,0,))
***IFI_COUNT_A+_IM_USA=SUM(IF((IFI_Level="A+")AND(Country="USA")AND(Type="IM"),1,0,))
***IFI_COUNT_E_IM_Vietnam=SUM(IF((IFI_Level="E")AND(Country="Vietnam")AND(Type="IM"),1,0,))
***IFI_COUNT_D_IM_Vietnam=SUM(IF((IFI_Level="D")AND(Country="Vietnam")AND(Type="IM"),1,0,))
***IFI_COUNT_C_IM_Vietnam=SUM(IF((IFI_Level="C")AND(Country="Vietnam")AND(Type="IM"),1,0,))
***IFI_COUNT_B_IM_Vietnam=SUM(IF((IFI_Level="B")AND(Country="Vietnam")AND(Type="IM"),1,0,))
***IFI_COUNT_A_IM_Vietnam=SUM(IF((IFI_Level="A")AND(Country="Vietnam")AND(Type="IM"),1,0,))
***IFI_COUNT_A+_IM_Vietnam=SUM(IF((IFI_Level="A+")AND(Country="Vietnam")AND(Type="IM"),1,0,))
***IFI_COUNT_E_AO_Australia=SUM(IF((IFI_Level="E")AND(Country="Australia")AND(Type="AO"),1,0,))
***IFI_COUNT_D_AO_Australia=SUM(IF((IFI_Level="D")AND(Country="Australia")AND(Type="AO"),1,0,))
***IFI_COUNT_C_AO_Australia=SUM(IF((IFI_Level="C")AND(Country="Australia")AND(Type="AO"),1,0,))
***IFI_COUNT_B_AO_Australia=SUM(IF((IFI_Level="B")AND(Country="Australia")AND(Type="AO"),1,0,))
***IFI_COUNT_A_AO_Australia=SUM(IF((IFI_Level="A")AND(Country="Australia")AND(Type="AO"),1,0,))
***IFI_COUNT_A+_AO_Australia=SUM(IF((IFI_Level="A+")AND(Country="Australia")AND(Type="AO"),1,0,))
***IFI_COUNT_E_AO_Austria=SUM(IF((IFI_Level="E")AND(Country="Austria")AND(Type="AO"),1,0,))
***IFI_COUNT_D_AO_Austria=SUM(IF((IFI_Level="D")AND(Country="Austria")AND(Type="AO"),1,0,))
***IFI_COUNT_C_AO_Austria=SUM(IF((IFI_Level="C")AND(Country="Austria")AND(Type="AO"),1,0,))
***IFI_COUNT_B_AO_Austria=SUM(IF((IFI_Level="B")AND(Country="Austria")AND(Type="AO"),1,0,))
***IFI_COUNT_A_AO_Austria=SUM(IF((IFI_Level="A")AND(Country="Austria")AND(Type="AO"),1,0,))
***IFI_COUNT_A+_AO_Austria=SUM(IF((IFI_Level="A+")AND(Country="Austria")AND(Type="AO"),1,0,))
***IFI_COUNT_E_AO_Belgium=SUM(IF((IFI_Level="E")AND(Country="Belgium")AND(Type="AO"),1,0,))
***IFI_COUNT_D_AO_Belgium=SUM(IF((IFI_Level="D")AND(Country="Belgium")AND(Type="AO"),1,0,))
***IFI_COUNT_C_AO_Belgium=SUM(IF((IFI_Level="C")AND(Country="Belgium")AND(Type="AO"),1,0,))
***IFI_COUNT_B_AO_Belgium=SUM(IF((IFI_Level="B")AND(Country="Belgium")AND(Type="AO"),1,0,))
***IFI_COUNT_A_AO_Belgium=SUM(IF((IFI_Level="A")AND(Country="Belgium")AND(Type="AO"),1,0,))
***IFI_COUNT_A+_AO_Belgium=SUM(IF((IFI_Level="A+")AND(Country="Belgium")AND(Type="AO"),1,0,))
***IFI_COUNT_E_AO_Bermuda=SUM(IF((IFI_Level="E")AND(Country="Bermuda")AND(Type="AO"),1,0,))
***IFI_COUNT_D_AO_Bermuda=SUM(IF((IFI_Level="D")AND(Country="Bermuda")AND(Type="AO"),1,0,))
***IFI_COUNT_C_AO_Bermuda=SUM(IF((IFI_Level="C")AND(Country="Bermuda")AND(Type="AO"),1,0,))
***IFI_COUNT_B_AO_Bermuda=SUM(IF((IFI_Level="B")AND(Country="Bermuda")AND(Type="AO"),1,0,))
***IFI_COUNT_A_AO_Bermuda=SUM(IF((IFI_Level="A")AND(Country="Bermuda")AND(Type="AO"),1,0,))
***IFI_COUNT_A+_AO_Bermuda=SUM(IF((IFI_Level="A+")AND(Country="Bermuda")AND(Type="AO"),1,0,))
***IFI_COUNT_E_AO_Botswana=SUM(IF((IFI_Level="E")AND(Country="Botswana")AND(Type="AO"),1,0,))
***IFI_COUNT_D_AO_Botswana=SUM(IF((IFI_Level="D")AND(Country="Botswana")AND(Type="AO"),1,0,))
***IFI_COUNT_C_AO_Botswana=SUM(IF((IFI_Level="C")AND(Country="Botswana")AND(Type="AO"),1,0,))
***IFI_COUNT_B_AO_Botswana=SUM(IF((IFI_Level="B")AND(Country="Botswana")AND(Type="AO"),1,0,))
***IFI_COUNT_A_AO_Botswana=SUM(IF((IFI_Level="A")AND(Country="Botswana")AND(Type="AO"),1,0,))
***IFI_COUNT_A+_AO_Botswana=SUM(IF((IFI_Level="A+")AND(Country="Botswana")AND(Type="AO"),1,0,))
***IFI_COUNT_E_AO_Brazil=SUM(IF((IFI_Level="E")AND(Country="Brazil")AND(Type="AO"),1,0,))
***IFI_COUNT_D_AO_Brazil=SUM(IF((IFI_Level="D")AND(Country="Brazil")AND(Type="AO"),1,0,))
***IFI_COUNT_C_AO_Brazil=SUM(IF((IFI_Level="C")AND(Country="Brazil")AND(Type="AO"),1,0,))
***IFI_COUNT_B_AO_Brazil=SUM(IF((IFI_Level="B")AND(Country="Brazil")AND(Type="AO"),1,0,))
***IFI_COUNT_A_AO_Brazil=SUM(IF((IFI_Level="A")AND(Country="Brazil")AND(Type="AO"),1,0,))
***IFI_COUNT_A+_AO_Brazil=SUM(IF((IFI_Level="A+")AND(Country="Brazil")AND(Type="AO"),1,0,))
***IFI_COUNT_E_AO_Canada=SUM(IF((IFI_Level="E")AND(Country="Canada")AND(Type="AO"),1,0,))
***IFI_COUNT_D_AO_Canada=SUM(IF((IFI_Level="D")AND(Country="Canada")AND(Type="AO"),1,0,))
***IFI_COUNT_C_AO_Canada=SUM(IF((IFI_Level="C")AND(Country="Canada")AND(Type="AO"),1,0,))
***IFI_COUNT_B_AO_Canada=SUM(IF((IFI_Level="B")AND(Country="Canada")AND(Type="AO"),1,0,))
***IFI_COUNT_A_AO_Canada=SUM(IF((IFI_Level="A")AND(Country="Canada")AND(Type="AO"),1,0,))
***IFI_COUNT_A+_AO_Canada=SUM(IF((IFI_Level="A+")AND(Country="Canada")AND(Type="AO"),1,0,))
***IFI_COUNT_E_AO_China=SUM(IF((IFI_Level="E")AND(Country="China")AND(Type="AO"),1,0,))
***IFI_COUNT_D_AO_China=SUM(IF((IFI_Level="D")AND(Country="China")AND(Type="AO"),1,0,))
***IFI_COUNT_C_AO_China=SUM(IF((IFI_Level="C")AND(Country="China")AND(Type="AO"),1,0,))
***IFI_COUNT_B_AO_China=SUM(IF((IFI_Level="B")AND(Country="China")AND(Type="AO"),1,0,))
***IFI_COUNT_A_AO_China=SUM(IF((IFI_Level="A")AND(Country="China")AND(Type="AO"),1,0,))
***IFI_COUNT_A+_AO_China=SUM(IF((IFI_Level="A+")AND(Country="China")AND(Type="AO"),1,0,))
***IFI_COUNT_E_AO_Colombia=SUM(IF((IFI_Level="E")AND(Country="Colombia")AND(Type="AO"),1,0,))
***IFI_COUNT_D_AO_Colombia=SUM(IF((IFI_Level="D")AND(Country="Colombia")AND(Type="AO"),1,0,))
***IFI_COUNT_C_AO_Colombia=SUM(IF((IFI_Level="C")AND(Country="Colombia")AND(Type="AO"),1,0,))
***IFI_COUNT_B_AO_Colombia=SUM(IF((IFI_Level="B")AND(Country="Colombia")AND(Type="AO"),1,0,))
***IFI_COUNT_A_AO_Colombia=SUM(IF((IFI_Level="A")AND(Country="Colombia")AND(Type="AO"),1,0,))
***IFI_COUNT_A+_AO_Colombia=SUM(IF((IFI_Level="A+")AND(Country="Colombia")AND(Type="AO"),1,0,))
***IFI_COUNT_E_AO_Denmark=SUM(IF((IFI_Level="E")AND(Country="Denmark")AND(Type="AO"),1,0,))
***IFI_COUNT_D_AO_Denmark=SUM(IF((IFI_Level="D")AND(Country="Denmark")AND(Type="AO"),1,0,))
***IFI_COUNT_C_AO_Denmark=SUM(IF((IFI_Level="C")AND(Country="Denmark")AND(Type="AO"),1,0,))
***IFI_COUNT_B_AO_Denmark=SUM(IF((IFI_Level="B")AND(Country="Denmark")AND(Type="AO"),1,0,))
***IFI_COUNT_A_AO_Denmark=SUM(IF((IFI_Level="A")AND(Country="Denmark")AND(Type="AO"),1,0,))
***IFI_COUNT_A+_AO_Denmark=SUM(IF((IFI_Level="A+")AND(Country="Denmark")AND(Type="AO"),1,0,))
***IFI_COUNT_E_AO_Estonia=SUM(IF((IFI_Level="E")AND(Country="Estonia")AND(Type="AO"),1,0,))
***IFI_COUNT_D_AO_Estonia=SUM(IF((IFI_Level="D")AND(Country="Estonia")AND(Type="AO"),1,0,))
***IFI_COUNT_C_AO_Estonia=SUM(IF((IFI_Level="C")AND(Country="Estonia")AND(Type="AO"),1,0,))
***IFI_COUNT_B_AO_Estonia=SUM(IF((IFI_Level="B")AND(Country="Estonia")AND(Type="AO"),1,0,))
***IFI_COUNT_A_AO_Estonia=SUM(IF((IFI_Level="A")AND(Country="Estonia")AND(Type="AO"),1,0,))
***IFI_COUNT_A+_AO_Estonia=SUM(IF((IFI_Level="A+")AND(Country="Estonia")AND(Type="AO"),1,0,))
***IFI_COUNT_E_AO_Finland=SUM(IF((IFI_Level="E")AND(Country="Finland")AND(Type="AO"),1,0,))
***IFI_COUNT_D_AO_Finland=SUM(IF((IFI_Level="D")AND(Country="Finland")AND(Type="AO"),1,0,))
***IFI_COUNT_C_AO_Finland=SUM(IF((IFI_Level="C")AND(Country="Finland")AND(Type="AO"),1,0,))
***IFI_COUNT_B_AO_Finland=SUM(IF((IFI_Level="B")AND(Country="Finland")AND(Type="AO"),1,0,))
***IFI_COUNT_A_AO_Finland=SUM(IF((IFI_Level="A")AND(Country="Finland")AND(Type="AO"),1,0,))
***IFI_COUNT_A+_AO_Finland=SUM(IF((IFI_Level="A+")AND(Country="Finland")AND(Type="AO"),1,0,))
***IFI_COUNT_E_AO_France=SUM(IF((IFI_Level="E")AND(Country="France")AND(Type="AO"),1,0,))
***IFI_COUNT_D_AO_France=SUM(IF((IFI_Level="D")AND(Country="France")AND(Type="AO"),1,0,))
***IFI_COUNT_C_AO_France=SUM(IF((IFI_Level="C")AND(Country="France")AND(Type="AO"),1,0,))
***IFI_COUNT_B_AO_France=SUM(IF((IFI_Level="B")AND(Country="France")AND(Type="AO"),1,0,))
***IFI_COUNT_A_AO_France=SUM(IF((IFI_Level="A")AND(Country="France")AND(Type="AO"),1,0,))
***IFI_COUNT_A+_AO_France=SUM(IF((IFI_Level="A+")AND(Country="France")AND(Type="AO"),1,0,))
***IFI_COUNT_E_AO_Germany=SUM(IF((IFI_Level="E")AND(Country="Germany")AND(Type="AO"),1,0,))
***IFI_COUNT_D_AO_Germany=SUM(IF((IFI_Level="D")AND(Country="Germany")AND(Type="AO"),1,0,))
***IFI_COUNT_C_AO_Germany=SUM(IF((IFI_Level="C")AND(Country="Germany")AND(Type="AO"),1,0,))
***IFI_COUNT_B_AO_Germany=SUM(IF((IFI_Level="B")AND(Country="Germany")AND(Type="AO"),1,0,))
***IFI_COUNT_A_AO_Germany=SUM(IF((IFI_Level="A")AND(Country="Germany")AND(Type="AO"),1,0,))
***IFI_COUNT_A+_AO_Germany=SUM(IF((IFI_Level="A+")AND(Country="Germany")AND(Type="AO"),1,0,))
***IFI_COUNT_E_AO_Hong Kong=SUM(IF((IFI_Level="E")AND(Country="Hong Kong")AND(Type="AO"),1,0,))
***IFI_COUNT_D_AO_Hong Kong=SUM(IF((IFI_Level="D")AND(Country="Hong Kong")AND(Type="AO"),1,0,))
***IFI_COUNT_C_AO_Hong Kong=SUM(IF((IFI_Level="C")AND(Country="Hong Kong")AND(Type="AO"),1,0,))
***IFI_COUNT_B_AO_Hong Kong=SUM(IF((IFI_Level="B")AND(Country="Hong Kong")AND(Type="AO"),1,0,))
***IFI_COUNT_A_AO_Hong Kong=SUM(IF((IFI_Level="A")AND(Country="Hong Kong")AND(Type="AO"),1,0,))
***IFI_COUNT_A+_AO_Hong Kong=SUM(IF((IFI_Level="A+")AND(Country="Hong Kong")AND(Type="AO"),1,0,))
***IFI_COUNT_E_AO_Iceland=SUM(IF((IFI_Level="E")AND(Country="Iceland")AND(Type="AO"),1,0,))
***IFI_COUNT_D_AO_Iceland=SUM(IF((IFI_Level="D")AND(Country="Iceland")AND(Type="AO"),1,0,))
***IFI_COUNT_C_AO_Iceland=SUM(IF((IFI_Level="C")AND(Country="Iceland")AND(Type="AO"),1,0,))
***IFI_COUNT_B_AO_Iceland=SUM(IF((IFI_Level="B")AND(Country="Iceland")AND(Type="AO"),1,0,))
***IFI_COUNT_A_AO_Iceland=SUM(IF((IFI_Level="A")AND(Country="Iceland")AND(Type="AO"),1,0,))
***IFI_COUNT_A+_AO_Iceland=SUM(IF((IFI_Level="A+")AND(Country="Iceland")AND(Type="AO"),1,0,))
***IFI_COUNT_E_AO_India=SUM(IF((IFI_Level="E")AND(Country="India")AND(Type="AO"),1,0,))
***IFI_COUNT_D_AO_India=SUM(IF((IFI_Level="D")AND(Country="India")AND(Type="AO"),1,0,))
***IFI_COUNT_C_AO_India=SUM(IF((IFI_Level="C")AND(Country="India")AND(Type="AO"),1,0,))
***IFI_COUNT_B_AO_India=SUM(IF((IFI_Level="B")AND(Country="India")AND(Type="AO"),1,0,))
***IFI_COUNT_A_AO_India=SUM(IF((IFI_Level="A")AND(Country="India")AND(Type="AO"),1,0,))
***IFI_COUNT_A+_AO_India=SUM(IF((IFI_Level="A+")AND(Country="India")AND(Type="AO"),1,0,))
***IFI_COUNT_E_AO_Indonesia=SUM(IF((IFI_Level="E")AND(Country="Indonesia")AND(Type="AO"),1,0,))
***IFI_COUNT_D_AO_Indonesia=SUM(IF((IFI_Level="D")AND(Country="Indonesia")AND(Type="AO"),1,0,))
***IFI_COUNT_C_AO_Indonesia=SUM(IF((IFI_Level="C")AND(Country="Indonesia")AND(Type="AO"),1,0,))
***IFI_COUNT_B_AO_Indonesia=SUM(IF((IFI_Level="B")AND(Country="Indonesia")AND(Type="AO"),1,0,))
***IFI_COUNT_A_AO_Indonesia=SUM(IF((IFI_Level="A")AND(Country="Indonesia")AND(Type="AO"),1,0,))
***IFI_COUNT_A+_AO_Indonesia=SUM(IF((IFI_Level="A+")AND(Country="Indonesia")AND(Type="AO"),1,0,))
***IFI_COUNT_E_AO_Ireland=SUM(IF((IFI_Level="E")AND(Country="Ireland")AND(Type="AO"),1,0,))
***IFI_COUNT_D_AO_Ireland=SUM(IF((IFI_Level="D")AND(Country="Ireland")AND(Type="AO"),1,0,))
***IFI_COUNT_C_AO_Ireland=SUM(IF((IFI_Level="C")AND(Country="Ireland")AND(Type="AO"),1,0,))
***IFI_COUNT_B_AO_Ireland=SUM(IF((IFI_Level="B")AND(Country="Ireland")AND(Type="AO"),1,0,))
***IFI_COUNT_A_AO_Ireland=SUM(IF((IFI_Level="A")AND(Country="Ireland")AND(Type="AO"),1,0,))
***IFI_COUNT_A+_AO_Ireland=SUM(IF((IFI_Level="A+")AND(Country="Ireland")AND(Type="AO"),1,0,))
***IFI_COUNT_E_AO_Italy=SUM(IF((IFI_Level="E")AND(Country="Italy")AND(Type="AO"),1,0,))
***IFI_COUNT_D_AO_Italy=SUM(IF((IFI_Level="D")AND(Country="Italy")AND(Type="AO"),1,0,))
***IFI_COUNT_C_AO_Italy=SUM(IF((IFI_Level="C")AND(Country="Italy")AND(Type="AO"),1,0,))
***IFI_COUNT_B_AO_Italy=SUM(IF((IFI_Level="B")AND(Country="Italy")AND(Type="AO"),1,0,))
***IFI_COUNT_A_AO_Italy=SUM(IF((IFI_Level="A")AND(Country="Italy")AND(Type="AO"),1,0,))
***IFI_COUNT_A+_AO_Italy=SUM(IF((IFI_Level="A+")AND(Country="Italy")AND(Type="AO"),1,0,))
***IFI_COUNT_E_AO_Japan=SUM(IF((IFI_Level="E")AND(Country="Japan")AND(Type="AO"),1,0,))
***IFI_COUNT_D_AO_Japan=SUM(IF((IFI_Level="D")AND(Country="Japan")AND(Type="AO"),1,0,))
***IFI_COUNT_C_AO_Japan=SUM(IF((IFI_Level="C")AND(Country="Japan")AND(Type="AO"),1,0,))
***IFI_COUNT_B_AO_Japan=SUM(IF((IFI_Level="B")AND(Country="Japan")AND(Type="AO"),1,0,))
***IFI_COUNT_A_AO_Japan=SUM(IF((IFI_Level="A")AND(Country="Japan")AND(Type="AO"),1,0,))
***IFI_COUNT_A+_AO_Japan=SUM(IF((IFI_Level="A+")AND(Country="Japan")AND(Type="AO"),1,0,))
***IFI_COUNT_E_AO_Liechtenstein=SUM(IF((IFI_Level="E")AND(Country="Liechtenstein")AND(Type="AO"),1,0,))
***IFI_COUNT_D_AO_Liechtenstein=SUM(IF((IFI_Level="D")AND(Country="Liechtenstein")AND(Type="AO"),1,0,))
***IFI_COUNT_C_AO_Liechtenstein=SUM(IF((IFI_Level="C")AND(Country="Liechtenstein")AND(Type="AO"),1,0,))
***IFI_COUNT_B_AO_Liechtenstein=SUM(IF((IFI_Level="B")AND(Country="Liechtenstein")AND(Type="AO"),1,0,))
***IFI_COUNT_A_AO_Liechtenstein=SUM(IF((IFI_Level="A")AND(Country="Liechtenstein")AND(Type="AO"),1,0,))
***IFI_COUNT_A+_AO_Liechtenstein=SUM(IF((IFI_Level="A+")AND(Country="Liechtenstein")AND(Type="AO"),1,0,))
***IFI_COUNT_E_AO_Luxembourg=SUM(IF((IFI_Level="E")AND(Country="Luxembourg")AND(Type="AO"),1,0,))
***IFI_COUNT_D_AO_Luxembourg=SUM(IF((IFI_Level="D")AND(Country="Luxembourg")AND(Type="AO"),1,0,))
***IFI_COUNT_C_AO_Luxembourg=SUM(IF((IFI_Level="C")AND(Country="Luxembourg")AND(Type="AO"),1,0,))
***IFI_COUNT_B_AO_Luxembourg=SUM(IF((IFI_Level="B")AND(Country="Luxembourg")AND(Type="AO"),1,0,))
***IFI_COUNT_A_AO_Luxembourg=SUM(IF((IFI_Level="A")AND(Country="Luxembourg")AND(Type="AO"),1,0,))
***IFI_COUNT_A+_AO_Luxembourg=SUM(IF((IFI_Level="A+")AND(Country="Luxembourg")AND(Type="AO"),1,0,))
***IFI_COUNT_E_AO_Malaysia=SUM(IF((IFI_Level="E")AND(Country="Malaysia")AND(Type="AO"),1,0,))
***IFI_COUNT_D_AO_Malaysia=SUM(IF((IFI_Level="D")AND(Country="Malaysia")AND(Type="AO"),1,0,))
***IFI_COUNT_C_AO_Malaysia=SUM(IF((IFI_Level="C")AND(Country="Malaysia")AND(Type="AO"),1,0,))
***IFI_COUNT_B_AO_Malaysia=SUM(IF((IFI_Level="B")AND(Country="Malaysia")AND(Type="AO"),1,0,))
***IFI_COUNT_A_AO_Malaysia=SUM(IF((IFI_Level="A")AND(Country="Malaysia")AND(Type="AO"),1,0,))
***IFI_COUNT_A+_AO_Malaysia=SUM(IF((IFI_Level="A+")AND(Country="Malaysia")AND(Type="AO"),1,0,))
***IFI_COUNT_E_AO_Mauritius=SUM(IF((IFI_Level="E")AND(Country="Mauritius")AND(Type="AO"),1,0,))
***IFI_COUNT_D_AO_Mauritius=SUM(IF((IFI_Level="D")AND(Country="Mauritius")AND(Type="AO"),1,0,))
***IFI_COUNT_C_AO_Mauritius=SUM(IF((IFI_Level="C")AND(Country="Mauritius")AND(Type="AO"),1,0,))
***IFI_COUNT_B_AO_Mauritius=SUM(IF((IFI_Level="B")AND(Country="Mauritius")AND(Type="AO"),1,0,))
***IFI_COUNT_A_AO_Mauritius=SUM(IF((IFI_Level="A")AND(Country="Mauritius")AND(Type="AO"),1,0,))
***IFI_COUNT_A+_AO_Mauritius=SUM(IF((IFI_Level="A+")AND(Country="Mauritius")AND(Type="AO"),1,0,))
***IFI_COUNT_E_AO_Namibia=SUM(IF((IFI_Level="E")AND(Country="Namibia")AND(Type="AO"),1,0,))
***IFI_COUNT_D_AO_Namibia=SUM(IF((IFI_Level="D")AND(Country="Namibia")AND(Type="AO"),1,0,))
***IFI_COUNT_C_AO_Namibia=SUM(IF((IFI_Level="C")AND(Country="Namibia")AND(Type="AO"),1,0,))
***IFI_COUNT_B_AO_Namibia=SUM(IF((IFI_Level="B")AND(Country="Namibia")AND(Type="AO"),1,0,))
***IFI_COUNT_A_AO_Namibia=SUM(IF((IFI_Level="A")AND(Country="Namibia")AND(Type="AO"),1,0,))
***IFI_COUNT_A+_AO_Namibia=SUM(IF((IFI_Level="A+")AND(Country="Namibia")AND(Type="AO"),1,0,))
***IFI_COUNT_E_AO_Netherlands=SUM(IF((IFI_Level="E")AND(Country="Netherlands")AND(Type="AO"),1,0,))
***IFI_COUNT_D_AO_Netherlands=SUM(IF((IFI_Level="D")AND(Country="Netherlands")AND(Type="AO"),1,0,))
***IFI_COUNT_C_AO_Netherlands=SUM(IF((IFI_Level="C")AND(Country="Netherlands")AND(Type="AO"),1,0,))
***IFI_COUNT_B_AO_Netherlands=SUM(IF((IFI_Level="B")AND(Country="Netherlands")AND(Type="AO"),1,0,))
***IFI_COUNT_A_AO_Netherlands=SUM(IF((IFI_Level="A")AND(Country="Netherlands")AND(Type="AO"),1,0,))
***IFI_COUNT_A+_AO_Netherlands=SUM(IF((IFI_Level="A+")AND(Country="Netherlands")AND(Type="AO"),1,0,))
***IFI_COUNT_E_AO_New Zealand=SUM(IF((IFI_Level="E")AND(Country="New Zealand")AND(Type="AO"),1,0,))
***IFI_COUNT_D_AO_New Zealand=SUM(IF((IFI_Level="D")AND(Country="New Zealand")AND(Type="AO"),1,0,))
***IFI_COUNT_C_AO_New Zealand=SUM(IF((IFI_Level="C")AND(Country="New Zealand")AND(Type="AO"),1,0,))
***IFI_COUNT_B_AO_New Zealand=SUM(IF((IFI_Level="B")AND(Country="New Zealand")AND(Type="AO"),1,0,))
***IFI_COUNT_A_AO_New Zealand=SUM(IF((IFI_Level="A")AND(Country="New Zealand")AND(Type="AO"),1,0,))
***IFI_COUNT_A+_AO_New Zealand=SUM(IF((IFI_Level="A+")AND(Country="New Zealand")AND(Type="AO"),1,0,))
***IFI_COUNT_E_AO_Nigeria=SUM(IF((IFI_Level="E")AND(Country="Nigeria")AND(Type="AO"),1,0,))
***IFI_COUNT_D_AO_Nigeria=SUM(IF((IFI_Level="D")AND(Country="Nigeria")AND(Type="AO"),1,0,))
***IFI_COUNT_C_AO_Nigeria=SUM(IF((IFI_Level="C")AND(Country="Nigeria")AND(Type="AO"),1,0,))
***IFI_COUNT_B_AO_Nigeria=SUM(IF((IFI_Level="B")AND(Country="Nigeria")AND(Type="AO"),1,0,))
***IFI_COUNT_A_AO_Nigeria=SUM(IF((IFI_Level="A")AND(Country="Nigeria")AND(Type="AO"),1,0,))
***IFI_COUNT_A+_AO_Nigeria=SUM(IF((IFI_Level="A+")AND(Country="Nigeria")AND(Type="AO"),1,0,))
***IFI_COUNT_E_AO_Norway=SUM(IF((IFI_Level="E")AND(Country="Norway")AND(Type="AO"),1,0,))
***IFI_COUNT_D_AO_Norway=SUM(IF((IFI_Level="D")AND(Country="Norway")AND(Type="AO"),1,0,))
***IFI_COUNT_C_AO_Norway=SUM(IF((IFI_Level="C")AND(Country="Norway")AND(Type="AO"),1,0,))
***IFI_COUNT_B_AO_Norway=SUM(IF((IFI_Level="B")AND(Country="Norway")AND(Type="AO"),1,0,))
***IFI_COUNT_A_AO_Norway=SUM(IF((IFI_Level="A")AND(Country="Norway")AND(Type="AO"),1,0,))
***IFI_COUNT_A+_AO_Norway=SUM(IF((IFI_Level="A+")AND(Country="Norway")AND(Type="AO"),1,0,))
***IFI_COUNT_E_AO_Peru=SUM(IF((IFI_Level="E")AND(Country="Peru")AND(Type="AO"),1,0,))
***IFI_COUNT_D_AO_Peru=SUM(IF((IFI_Level="D")AND(Country="Peru")AND(Type="AO"),1,0,))
***IFI_COUNT_C_AO_Peru=SUM(IF((IFI_Level="C")AND(Country="Peru")AND(Type="AO"),1,0,))
***IFI_COUNT_B_AO_Peru=SUM(IF((IFI_Level="B")AND(Country="Peru")AND(Type="AO"),1,0,))
***IFI_COUNT_A_AO_Peru=SUM(IF((IFI_Level="A")AND(Country="Peru")AND(Type="AO"),1,0,))
***IFI_COUNT_A+_AO_Peru=SUM(IF((IFI_Level="A+")AND(Country="Peru")AND(Type="AO"),1,0,))
***IFI_COUNT_E_AO_Puerto Rico=SUM(IF((IFI_Level="E")AND(Country="Puerto Rico")AND(Type="AO"),1,0,))
***IFI_COUNT_D_AO_Puerto Rico=SUM(IF((IFI_Level="D")AND(Country="Puerto Rico")AND(Type="AO"),1,0,))
***IFI_COUNT_C_AO_Puerto Rico=SUM(IF((IFI_Level="C")AND(Country="Puerto Rico")AND(Type="AO"),1,0,))
***IFI_COUNT_B_AO_Puerto Rico=SUM(IF((IFI_Level="B")AND(Country="Puerto Rico")AND(Type="AO"),1,0,))
***IFI_COUNT_A_AO_Puerto Rico=SUM(IF((IFI_Level="A")AND(Country="Puerto Rico")AND(Type="AO"),1,0,))
***IFI_COUNT_A+_AO_Puerto Rico=SUM(IF((IFI_Level="A+")AND(Country="Puerto Rico")AND(Type="AO"),1,0,))
***IFI_COUNT_E_AO_Russia=SUM(IF((IFI_Level="E")AND(Country="Russia")AND(Type="AO"),1,0,))
***IFI_COUNT_D_AO_Russia=SUM(IF((IFI_Level="D")AND(Country="Russia")AND(Type="AO"),1,0,))
***IFI_COUNT_C_AO_Russia=SUM(IF((IFI_Level="C")AND(Country="Russia")AND(Type="AO"),1,0,))
***IFI_COUNT_B_AO_Russia=SUM(IF((IFI_Level="B")AND(Country="Russia")AND(Type="AO"),1,0,))
***IFI_COUNT_A_AO_Russia=SUM(IF((IFI_Level="A")AND(Country="Russia")AND(Type="AO"),1,0,))
***IFI_COUNT_A+_AO_Russia=SUM(IF((IFI_Level="A+")AND(Country="Russia")AND(Type="AO"),1,0,))
***IFI_COUNT_E_AO_Saudi Arabia=SUM(IF((IFI_Level="E")AND(Country="Saudi Arabia")AND(Type="AO"),1,0,))
***IFI_COUNT_D_AO_Saudi Arabia=SUM(IF((IFI_Level="D")AND(Country="Saudi Arabia")AND(Type="AO"),1,0,))
***IFI_COUNT_C_AO_Saudi Arabia=SUM(IF((IFI_Level="C")AND(Country="Saudi Arabia")AND(Type="AO"),1,0,))
***IFI_COUNT_B_AO_Saudi Arabia=SUM(IF((IFI_Level="B")AND(Country="Saudi Arabia")AND(Type="AO"),1,0,))
***IFI_COUNT_A_AO_Saudi Arabia=SUM(IF((IFI_Level="A")AND(Country="Saudi Arabia")AND(Type="AO"),1,0,))
***IFI_COUNT_A+_AO_Saudi Arabia=SUM(IF((IFI_Level="A+")AND(Country="Saudi Arabia")AND(Type="AO"),1,0,))
***IFI_COUNT_E_AO_Singapore=SUM(IF((IFI_Level="E")AND(Country="Singapore")AND(Type="AO"),1,0,))
***IFI_COUNT_D_AO_Singapore=SUM(IF((IFI_Level="D")AND(Country="Singapore")AND(Type="AO"),1,0,))
***IFI_COUNT_C_AO_Singapore=SUM(IF((IFI_Level="C")AND(Country="Singapore")AND(Type="AO"),1,0,))
***IFI_COUNT_B_AO_Singapore=SUM(IF((IFI_Level="B")AND(Country="Singapore")AND(Type="AO"),1,0,))
***IFI_COUNT_A_AO_Singapore=SUM(IF((IFI_Level="A")AND(Country="Singapore")AND(Type="AO"),1,0,))
***IFI_COUNT_A+_AO_Singapore=SUM(IF((IFI_Level="A+")AND(Country="Singapore")AND(Type="AO"),1,0,))
***IFI_COUNT_E_AO_South Africa=SUM(IF((IFI_Level="E")AND(Country="South Africa")AND(Type="AO"),1,0,))
***IFI_COUNT_D_AO_South Africa=SUM(IF((IFI_Level="D")AND(Country="South Africa")AND(Type="AO"),1,0,))
***IFI_COUNT_C_AO_South Africa=SUM(IF((IFI_Level="C")AND(Country="South Africa")AND(Type="AO"),1,0,))
***IFI_COUNT_B_AO_South Africa=SUM(IF((IFI_Level="B")AND(Country="South Africa")AND(Type="AO"),1,0,))
***IFI_COUNT_A_AO_South Africa=SUM(IF((IFI_Level="A")AND(Country="South Africa")AND(Type="AO"),1,0,))
***IFI_COUNT_A+_AO_South Africa=SUM(IF((IFI_Level="A+")AND(Country="South Africa")AND(Type="AO"),1,0,))
***IFI_COUNT_E_AO_Spain=SUM(IF((IFI_Level="E")AND(Country="Spain")AND(Type="AO"),1,0,))
***IFI_COUNT_D_AO_Spain=SUM(IF((IFI_Level="D")AND(Country="Spain")AND(Type="AO"),1,0,))
***IFI_COUNT_C_AO_Spain=SUM(IF((IFI_Level="C")AND(Country="Spain")AND(Type="AO"),1,0,))
***IFI_COUNT_B_AO_Spain=SUM(IF((IFI_Level="B")AND(Country="Spain")AND(Type="AO"),1,0,))
***IFI_COUNT_A_AO_Spain=SUM(IF((IFI_Level="A")AND(Country="Spain")AND(Type="AO"),1,0,))
***IFI_COUNT_A+_AO_Spain=SUM(IF((IFI_Level="A+")AND(Country="Spain")AND(Type="AO"),1,0,))
***IFI_COUNT_E_AO_Sweden=SUM(IF((IFI_Level="E")AND(Country="Sweden")AND(Type="AO"),1,0,))
***IFI_COUNT_D_AO_Sweden=SUM(IF((IFI_Level="D")AND(Country="Sweden")AND(Type="AO"),1,0,))
***IFI_COUNT_C_AO_Sweden=SUM(IF((IFI_Level="C")AND(Country="Sweden")AND(Type="AO"),1,0,))
***IFI_COUNT_B_AO_Sweden=SUM(IF((IFI_Level="B")AND(Country="Sweden")AND(Type="AO"),1,0,))
***IFI_COUNT_A_AO_Sweden=SUM(IF((IFI_Level="A")AND(Country="Sweden")AND(Type="AO"),1,0,))
***IFI_COUNT_A+_AO_Sweden=SUM(IF((IFI_Level="A+")AND(Country="Sweden")AND(Type="AO"),1,0,))
***IFI_COUNT_E_AO_Switzerland=SUM(IF((IFI_Level="E")AND(Country="Switzerland")AND(Type="AO"),1,0,))
***IFI_COUNT_D_AO_Switzerland=SUM(IF((IFI_Level="D")AND(Country="Switzerland")AND(Type="AO"),1,0,))
***IFI_COUNT_C_AO_Switzerland=SUM(IF((IFI_Level="C")AND(Country="Switzerland")AND(Type="AO"),1,0,))
***IFI_COUNT_B_AO_Switzerland=SUM(IF((IFI_Level="B")AND(Country="Switzerland")AND(Type="AO"),1,0,))
***IFI_COUNT_A_AO_Switzerland=SUM(IF((IFI_Level="A")AND(Country="Switzerland")AND(Type="AO"),1,0,))
***IFI_COUNT_A+_AO_Switzerland=SUM(IF((IFI_Level="A+")AND(Country="Switzerland")AND(Type="AO"),1,0,))
***IFI_COUNT_E_AO_Thailand=SUM(IF((IFI_Level="E")AND(Country="Thailand")AND(Type="AO"),1,0,))
***IFI_COUNT_D_AO_Thailand=SUM(IF((IFI_Level="D")AND(Country="Thailand")AND(Type="AO"),1,0,))
***IFI_COUNT_C_AO_Thailand=SUM(IF((IFI_Level="C")AND(Country="Thailand")AND(Type="AO"),1,0,))
***IFI_COUNT_B_AO_Thailand=SUM(IF((IFI_Level="B")AND(Country="Thailand")AND(Type="AO"),1,0,))
***IFI_COUNT_A_AO_Thailand=SUM(IF((IFI_Level="A")AND(Country="Thailand")AND(Type="AO"),1,0,))
***IFI_COUNT_A+_AO_Thailand=SUM(IF((IFI_Level="A+")AND(Country="Thailand")AND(Type="AO"),1,0,))
***IFI_COUNT_E_AO_Turkey=SUM(IF((IFI_Level="E")AND(Country="Turkey")AND(Type="AO"),1,0,))
***IFI_COUNT_D_AO_Turkey=SUM(IF((IFI_Level="D")AND(Country="Turkey")AND(Type="AO"),1,0,))
***IFI_COUNT_C_AO_Turkey=SUM(IF((IFI_Level="C")AND(Country="Turkey")AND(Type="AO"),1,0,))
***IFI_COUNT_B_AO_Turkey=SUM(IF((IFI_Level="B")AND(Country="Turkey")AND(Type="AO"),1,0,))
***IFI_COUNT_A_AO_Turkey=SUM(IF((IFI_Level="A")AND(Country="Turkey")AND(Type="AO"),1,0,))
***IFI_COUNT_A+_AO_Turkey=SUM(IF((IFI_Level="A+")AND(Country="Turkey")AND(Type="AO"),1,0,))
***IFI_COUNT_E_AO_UAE=SUM(IF((IFI_Level="E")AND(Country="UAE")AND(Type="AO"),1,0,))
***IFI_COUNT_D_AO_UAE=SUM(IF((IFI_Level="D")AND(Country="UAE")AND(Type="AO"),1,0,))
***IFI_COUNT_C_AO_UAE=SUM(IF((IFI_Level="C")AND(Country="UAE")AND(Type="AO"),1,0,))
***IFI_COUNT_B_AO_UAE=SUM(IF((IFI_Level="B")AND(Country="UAE")AND(Type="AO"),1,0,))
***IFI_COUNT_A_AO_UAE=SUM(IF((IFI_Level="A")AND(Country="UAE")AND(Type="AO"),1,0,))
***IFI_COUNT_A+_AO_UAE=SUM(IF((IFI_Level="A+")AND(Country="UAE")AND(Type="AO"),1,0,))
***IFI_COUNT_E_AO_UK=SUM(IF((IFI_Level="E")AND(Country="UK")AND(Type="AO"),1,0,))
***IFI_COUNT_D_AO_UK=SUM(IF((IFI_Level="D")AND(Country="UK")AND(Type="AO"),1,0,))
***IFI_COUNT_C_AO_UK=SUM(IF((IFI_Level="C")AND(Country="UK")AND(Type="AO"),1,0,))
***IFI_COUNT_B_AO_UK=SUM(IF((IFI_Level="B")AND(Country="UK")AND(Type="AO"),1,0,))
***IFI_COUNT_A_AO_UK=SUM(IF((IFI_Level="A")AND(Country="UK")AND(Type="AO"),1,0,))
***IFI_COUNT_A+_AO_UK=SUM(IF((IFI_Level="A+")AND(Country="UK")AND(Type="AO"),1,0,))
***IFI_COUNT_E_AO_USA=SUM(IF((IFI_Level="E")AND(Country="USA")AND(Type="AO"),1,0,))
***IFI_COUNT_D_AO_USA=SUM(IF((IFI_Level="D")AND(Country="USA")AND(Type="AO"),1,0,))
***IFI_COUNT_C_AO_USA=SUM(IF((IFI_Level="C")AND(Country="USA")AND(Type="AO"),1,0,))
***IFI_COUNT_B_AO_USA=SUM(IF((IFI_Level="B")AND(Country="USA")AND(Type="AO"),1,0,))
***IFI_COUNT_A_AO_USA=SUM(IF((IFI_Level="A")AND(Country="USA")AND(Type="AO"),1,0,))
***IFI_COUNT_A+_AO_USA=SUM(IF((IFI_Level="A+")AND(Country="USA")AND(Type="AO"),1,0,))
***IFI_COUNT_E_AO_Vietnam=SUM(IF((IFI_Level="E")AND(Country="Vietnam")AND(Type="AO"),1,0,))
***IFI_COUNT_D_AO_Vietnam=SUM(IF((IFI_Level="D")AND(Country="Vietnam")AND(Type="AO"),1,0,))
***IFI_COUNT_C_AO_Vietnam=SUM(IF((IFI_Level="C")AND(Country="Vietnam")AND(Type="AO"),1,0,))
***IFI_COUNT_B_AO_Vietnam=SUM(IF((IFI_Level="B")AND(Country="Vietnam")AND(Type="AO"),1,0,))
***IFI_COUNT_A_AO_Vietnam=SUM(IF((IFI_Level="A")AND(Country="Vietnam")AND(Type="AO"),1,0,))
***IFI_COUNT_A+_AO_Vietnam=SUM(IF((IFI_Level="A+")AND(Country="Vietnam")AND(Type="AO"),1,0,))
